import type { JobCard } from "./types";

export const sampleJobs: JobCard[] = [
  {
    id: "1",
    company: "Neon Labs",
    role: "Senior Frontend Engineer",
    location: "San Francisco, CA",
    salary: "$160k - $210k",
    manager: {
      name: "Marcus Chen",
      title: "VP of Engineering",
      tagline: "We ship fast and break conventions, not production.",
      photo: "/assets/managers/marcus.jpg",
    },
    hr: {
      name: "Sarah Kim",
      title: "Senior Technical Recruiter",
      photo: "/assets/hr/sarah.jpg",
      email: "sarah.kim@neonlabs.io",
      phone: "+1 (415) 555-0142",
    },
    tags: ["React", "TypeScript", "Remote-Friendly", "Series B"],
  },
  {
    id: "2",
    company: "Verdant Health",
    role: "Full-Stack Developer",
    location: "Austin, TX",
    salary: "$130k - $175k",
    manager: {
      name: "Priya Patel",
      title: "Director of Product Engineering",
      tagline: "Healthcare meets cutting-edge tech. Join us.",
      photo: "/assets/managers/priya.jpg",
      video: "/assets/managers/priya-intro.mp4",
    },
    hr: {
      name: "James Thornton",
      title: "People Operations Lead",
      photo: "/assets/hr/james.jpg",
      email: "j.thornton@verdanthealth.com",
      phone: "+1 (512) 555-0198",
    },
    tags: ["Node.js", "React", "Healthcare", "Hybrid"],
  },
  {
    id: "3",
    company: "Cobalt Robotics",
    role: "ML Platform Engineer",
    location: "Boston, MA",
    salary: "$180k - $240k",
    manager: {
      name: "David Okonkwo",
      title: "Head of ML Infrastructure",
      tagline: "Building the backbone for autonomous systems.",
      photo: "/assets/managers/david.jpg",
    },
    hr: {
      name: "Emily Vasquez",
      title: "Technical Talent Partner",
      photo: "/assets/hr/emily.jpg",
      email: "emily.v@cobaltrobotics.ai",
    },
    tags: ["Python", "Kubernetes", "ML/AI", "On-Site"],
  },
  {
    id: "4",
    company: "Firefly Finance",
    role: "Backend Engineer",
    location: "New York, NY",
    salary: "$150k - $200k",
    manager: {
      name: "Rachel Nguyen",
      title: "Engineering Manager, Payments",
      tagline: "Real-time payments, real impact. Millions of transactions daily.",
      photo: "/assets/managers/rachel.jpg",
      video: "/assets/managers/rachel-intro.mp4",
    },
    hr: {
      name: "Tom Bradley",
      title: "Recruitment Lead",
      photo: "/assets/hr/tom.jpg",
      email: "tom.bradley@fireflyfinance.com",
      phone: "+1 (212) 555-0167",
    },
    tags: ["Go", "PostgreSQL", "Fintech", "On-Site"],
  },
  {
    id: "5",
    company: "Solstice Studios",
    role: "Creative Technologist",
    location: "Los Angeles, CA",
    salary: "$120k - $160k",
    manager: {
      name: "Alex Rivera",
      title: "Creative Director",
      tagline: "Where art meets code. We make the internet beautiful.",
      photo: "/assets/managers/alex.jpg",
    },
    hr: {
      name: "Nina Okafor",
      title: "Talent Acquisition Specialist",
      photo: "/assets/hr/nina.jpg",
      email: "nina@solsticestudios.co",
      phone: "+1 (323) 555-0134",
    },
    tags: ["Three.js", "GSAP", "WebGL", "Remote"],
  },
];
