import type { JobCard } from "./types";

export const sampleJobs: JobCard[] = [
  {
    id: "1",
    company: "Stripe",
    role: "Backend Engineer, Core Technology",
    location: "Hybrid — South San Francisco, CA",
    salary: "$155,700 - $285,600",
    manager: {
      name: "David Singleton",
      title: "CTO",
      tagline: "We build the economic infrastructure for the internet.",
      photo: "/assets/managers/stripe-mgr.jpg",
    },
    hr: {
      name: "Sarah Chen",
      title: "Engineering Talent Partner",
      photo: "/assets/hr/stripe-hr.jpg",
      email: "recruiting@stripe.com",
    },
    tags: ["Go", "Java", "C++", "Distributed Systems", "Fintech"],
    description:
      "About the Role: This role involves designing, building, testing, and shipping code within Stripe's infrastructure organization. The position spans critical areas including Core Infrastructure, Developer Infrastructure, Data Infrastructure, Admin Platform, and Service Platform.\n\nWhat You'll Do: Build a great customer experience for internal and external Stripe teams using our infrastructure. Contribute to roadmap planning and prioritization efforts. Deliver value through a strong collaborative approach with multiple customers and stakeholders. Debug production issues across service layers.\n\nAbout Us: Stripe builds the most powerful and flexible tools for internet commerce. Whether you're creating a subscription service, an on-demand marketplace, or an e-commerce store, Stripe's infrastructure handles trillions of dollars in payments each year.",
    requirements: [
      "2-12+ years of professional hands-on software development experience",
      "Ability to write high quality code in Go, Java, C/C++, or similar languages",
      "Hands-on experience contributing to or building large-scale distributed systems",
      "Strong collaboration and communication abilities",
      "Customer-focused mindset with entrepreneurial orientation",
    ],
    benefits: [
      "Equity compensation",
      "Company bonus",
      "401(k) plan",
      "Medical, dental, and vision coverage",
      "Wellness stipends",
    ],
    teamSize: "Infrastructure org — multiple teams",
    culture: ["User-first", "Move with urgency", "High code quality", "50% in-office monthly"],
  },
  {
    id: "2",
    company: "Stripe",
    role: "Senior Staff Software Engineer, Developer Infrastructure",
    location: "South San Francisco, CA (On-site)",
    salary: "$271,200 - $406,800",
    manager: {
      name: "Raylene Yung",
      title: "VP of Engineering",
      tagline: "We support thousands of engineers across Ruby, Java, Go, Python, and TypeScript.",
      photo: "/assets/managers/stripe-mgr2.jpg",
    },
    hr: {
      name: "Michael Torres",
      title: "Senior Staff Recruiting Lead",
      photo: "/assets/hr/stripe-hr2.jpg",
      email: "recruiting@stripe.com",
    },
    tags: ["CI/CD", "Bazel", "Kubernetes", "Terraform", "Developer Productivity"],
    description:
      "About the Role: The Developer Infrastructure organization supports thousands of Stripe engineers across Ruby, Java, Go, Python, and TypeScript. This role focuses on ensuring the most productive place of an engineer's career by maintaining observability systems supporting 99.9995% uptime and regulatory compliance.\n\nWhat You'll Do: Develop architectural strategies and sustainable solutions for internal development processes. Lead and mentor engineering teams. Deploy AI development strategies company-wide. Measure engineering productivity and prioritize impactful initiatives.\n\nAbout Us: Stripe processes trillions of dollars for millions of businesses worldwide. Our developer infrastructure ensures every Stripe engineer can ship with confidence.",
    requirements: [
      "13+ years software development or DevOps experience",
      "BS/MS in Computer Science or related field",
      "Developer productivity tooling experience (code review, CI/CD, build systems)",
      "Cross-team project leadership and distributed systems reliability expertise",
      "Engineering mentorship experience and operational excellence",
    ],
    benefits: [
      "Equity compensation with annual refresh",
      "Company bonus",
      "401(k) plan",
      "Comprehensive medical, dental, and vision",
      "Wellness stipends",
    ],
    teamSize: "Developer Infrastructure org",
    culture: ["Engineering excellence", "High ownership", "50% in-office monthly", "AI-forward"],
  },
  {
    id: "3",
    company: "Stripe",
    role: "Software Engineer, New Grad",
    location: "South San Francisco or Seattle",
    salary: "$122,100 - $134,400",
    manager: {
      name: "Claire Hughes Johnson",
      title: "New Grad Program Lead",
      tagline: "End-to-end ownership of projects from your first week.",
      photo: "/assets/managers/stripe-mgr3.jpg",
    },
    hr: {
      name: "Jessica Park",
      title: "University Recruiter",
      photo: "/assets/hr/stripe-hr3.jpg",
      email: "university-recruiting@stripe.com",
    },
    tags: ["Full Stack", "New Grad", "Ruby", "Go", "Python"],
    description:
      "About the Role: Join Stripe's financial infrastructure platform as an early-career engineer. We emphasize end-to-end ownership of projects where you drive completion while collaborating across teams.\n\nWhat You'll Do: Collaborate on cross-functional initiatives with fellow engineers. Provide substantive feedback during code reviews and technical assessments. Maintain system reliability and scalability. Progress toward independent project ownership with mentorship.\n\nAbout Us: Stripe's New Grad program pairs you with experienced engineers, provides 2+ weeks of onboarding, and puts you on real teams solving real problems from day one.",
    requirements: [
      "Bachelor's or Master's in Computer Science (or related field) by summer 2026",
      "Programming experience through coursework, personal projects, or internships",
      "Collaborative coding experience in team settings",
      "Capacity to independently research and master unfamiliar systems with guidance",
    ],
    benefits: [
      "Equity compensation",
      "Company bonus opportunities",
      "401(k) plan",
      "Medical, dental, and vision coverage",
      "Wellness stipends",
    ],
    teamSize: "Varies by team placement",
    culture: ["Mentorship-heavy", "End-to-end ownership", "50% in-office", "Learn by doing"],
  },
  {
    id: "4",
    company: "Datadog",
    role: "Senior Software Engineer",
    location: "New York, NY or Boston, MA",
    salary: "$130,000 - $300,000",
    manager: {
      name: "Alexis Le-Quoc",
      title: "CTO & Co-founder",
      tagline: "We help engineers see inside any stack, any app, at any scale.",
      photo: "/assets/managers/datadog-mgr.jpg",
    },
    hr: {
      name: "Amanda Liu",
      title: "Senior Technical Recruiter",
      photo: "/assets/hr/datadog-hr.jpg",
      email: "recruiting@datadoghq.com",
    },
    tags: ["Go", "Python", "Redis", "Kafka", "Observability"],
    description:
      "About the Role: We seek engineers to work on critical infrastructure challenges at massive scale.\n\nWhat You'll Do: Resolve scaling bottlenecks in key services. Deploy features with progressive rollouts using feature flags. Investigate and fix production issues. Design architecture for high-traffic scenarios. Collaborate on strategic project prioritization.\n\nAbout Us: Datadog is the monitoring and security platform for cloud applications. We process trillions of data points per day, providing unified visibility into infrastructure, applications, logs, and security threats.",
    requirements: [
      "6+ years of software engineering experience",
      "Significant experience in one or more programming languages",
      "Demonstrated focus on code simplicity and performance",
      "Ability to design scalable architecture for high-volume systems",
      "BS/MS/PhD in a scientific field or equivalent professional experience",
    ],
    benefits: [
      "Healthcare, dental, and mental health coverage",
      "401(k) plan with employer match",
      "Equity compensation package",
      "Paid time off and fitness reimbursements",
      "Discounted employee stock purchase plan",
    ],
    teamSize: "Engineering — multiple teams",
    culture: ["Scale-obsessed", "Data-driven", "Fast-growth startup energy", "AI-enhanced development"],
  },
  {
    id: "5",
    company: "Vercel",
    role: "Software Engineer, CDN",
    location: "Hybrid — New York or San Francisco",
    salary: "$196,000 - $294,000",
    manager: {
      name: "Guillermo Rauch",
      title: "CEO & Founder",
      tagline: "We make the web faster for everyone.",
      photo: "/assets/managers/vercel-mgr.jpg",
    },
    hr: {
      name: "Rachel Kim",
      title: "Engineering Recruiter",
      photo: "/assets/hr/vercel-hr.jpg",
      email: "careers@vercel.com",
    },
    tags: ["Golang", "Kubernetes", "Terraform", "Networking", "Edge Computing"],
    description:
      "About the Role: Join Vercel's Edge team to enhance infrastructure, availability, and reliability. The Edge team orchestrates deployment, routing, and content serving through systems managing networking, TLS termination, routing, storage, caching, and edge services.\n\nWhat You'll Do: Combine system design, coding, and production debugging. Work alongside backend engineers and product teams to identify challenges, build tooling, and create automation. Scale high-performance cloud systems.\n\nAbout Us: Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. Vercel is the company behind Next.js.",
    requirements: [
      "5+ years relevant experience",
      "Deep expertise scaling high-performance cloud systems",
      "Strong knowledge of web servers and network protocols",
      "Proficiency in Golang",
      "Familiarity with cloud platforms (AWS, Google Cloud)",
    ],
    benefits: [
      "Competitive compensation with equity",
      "Inclusive healthcare coverage",
      "Mentorship and professional development",
      "Flexible time off",
      "Equipment and work-from-home budget",
    ],
    teamSize: "Edge team",
    culture: ["Remote-friendly", "Open source first", "Ship fast", "Developer experience obsessed"],
  },
  {
    id: "6",
    company: "Plaid",
    role: "Software Engineer, Platform",
    location: "New York, NY",
    salary: "$163,200 - $223,200",
    manager: {
      name: "Jean-Denis Greze",
      title: "CTO",
      tagline: "We power the tools millions of people rely on to live a healthier financial life.",
      photo: "/assets/managers/plaid-mgr.jpg",
    },
    hr: {
      name: "Lisa Martinez",
      title: "Technical Recruiter",
      photo: "/assets/hr/plaid-hr.jpg",
      email: "careers@plaid.com",
    },
    tags: ["Go", "Python", "MySQL", "Distributed Systems", "Fintech"],
    description:
      "About the Role: This position sits within Plaid's Platform Engineering organization, which focuses on core infrastructure, data platforms, storage, privacy, and developer efficiency.\n\nWhat You'll Do: Design, build, and maintain foundational infrastructure and internal platforms that empower all of Plaid's engineering teams to move quickly and safely. Build scalable distributed backend systems handling millions of daily requests. Develop storage and processing systems. Create CI/CD pipelines, monitoring systems, and self-service infrastructure platforms. Embed encryption, access controls, and audit logging into platform architecture.\n\nAbout Us: Plaid is a fintech company operating a network connecting 12,000+ financial institutions. Our products are used by companies like Venmo, SoFi, and major Fortune 500 banks.",
    requirements: [
      "2-4 years building and shipping complex backend systems or distributed platforms",
      "Proficiency in Go preferred; Python, Java, or C++ acceptable",
      "Deep understanding of system design, algorithms, and distributed architectures",
      "Familiarity with relational and NoSQL databases (MySQL/TiDB, PostgreSQL, MongoDB)",
      "Strong communication and collaborative skills",
    ],
    benefits: [
      "Comprehensive medical, dental, and vision coverage",
      "401(k) retirement plan",
      "Equity and/or commission eligibility",
      "Generous PTO",
      "Parental leave",
    ],
    teamSize: "Platform Engineering org",
    culture: ["Fintech mission-driven", "High engineering bar", "Cross-functional", "Move quickly and safely"],
  },
  {
    id: "7",
    company: "Plaid",
    role: "Senior Software Engineer, Fullstack",
    location: "New York, NY",
    salary: "$180,000 - $270,000",
    manager: {
      name: "William Hockey",
      title: "Engineering Director",
      tagline: "Design and build systems that power how millions connect to their finances.",
      photo: "/assets/managers/plaid-mgr2.jpg",
    },
    hr: {
      name: "David Chen",
      title: "Senior Recruiter",
      photo: "/assets/hr/plaid-hr2.jpg",
      email: "careers@plaid.com",
    },
    tags: ["TypeScript", "React", "MySQL", "Microservices", "Fintech"],
    description:
      "About the Role: Design and build the systems and experiences that power how millions of people connect to their finances. Work across the stack to build scalable backend services and APIs while crafting intuitive, high-quality frontend experiences.\n\nWhat You'll Do: Develop backend services using relational databases and create frontend applications. Collaborate with product managers and designers on feature delivery. Write clean, maintainable, and well-tested code through code reviews. Monitor production systems and troubleshoot performance issues. Mentor engineers and support team development.\n\nAbout Us: Plaid connects 12,000 financial institutions across the US, Canada, UK and Europe. Offices in San Francisco, New York, Washington D.C., London, and Amsterdam.",
    requirements: [
      "5+ years shipping production software systems",
      "Backend experience with MySQL and microservice architectures",
      "Proficiency in HTML, CSS, JavaScript, and modern frontend frameworks",
      "Strong system design and testing capabilities across stacks",
      "Engineering mentorship or leadership track record",
    ],
    benefits: [
      "Comprehensive medical, dental, and vision",
      "401(k) plan",
      "Equity compensation",
      "Generous PTO and parental leave",
      "Home office stipend",
    ],
    teamSize: "Product engineering",
    culture: ["Full-stack ownership", "Collaborative", "High-quality code", "Mission-driven fintech"],
  },
  {
    id: "8",
    company: "Google",
    role: "Software Engineer, L4",
    location: "Mountain View, CA (On-site)",
    salary: "$161,000 - $239,000",
    manager: {
      name: "Parisa Tabriz",
      title: "VP of Engineering, Chrome",
      tagline: "Organize the world's information and make it universally accessible.",
      photo: "/assets/managers/google-mgr.jpg",
    },
    hr: {
      name: "Jennifer Wu",
      title: "Technical Recruiter",
      photo: "/assets/hr/google-hr.jpg",
      email: "staffing@google.com",
    },
    tags: ["Python", "Java", "C++", "Machine Learning", "Go"],
    description:
      "About the Role: As a Software Engineer at Google, you work on projects of extraordinary complexity that touch billions of users. You design, develop, test, deploy, maintain, and improve software across Google's products.\n\nWhat You'll Do: Develop next-generation technologies that change how billions of users connect, explore, and interact. Build infrastructure, develop new solutions, or improve existing ones. Work across teams to solve problems at massive scale.\n\nAbout Us: Google's software engineers develop technologies used by billions of people. Our products include Search, Chrome, Android, YouTube, Cloud, and many more.",
    requirements: [
      "BS in Computer Science, related field, or equivalent practical experience",
      "2+ years of experience with one or more general purpose programming languages",
      "Experience with data structures, algorithms, and software design",
      "Experience building and shipping production software",
    ],
    benefits: [
      "24 weeks parental leave (birth parents), 18 weeks (non-birth)",
      "Comprehensive medical, dental, and vision insurance",
      "Employee assistance programs focused on mental health",
      "Onsite wellness and fitness centers",
      "Free meals and snacks",
    ],
    teamSize: "Varies by org — typically 5-12 per team",
    culture: ["20% projects", "Data-driven decisions", "Psychological safety", "Impact at scale"],
  },
  {
    id: "9",
    company: "Meta",
    role: "Software Engineer (E4)",
    location: "Menlo Park, CA (On-site)",
    salary: "$176,000 - $290,000",
    manager: {
      name: "Andrew Bosworth",
      title: "CTO",
      tagline: "Build technology that brings the world closer together.",
      photo: "/assets/managers/meta-mgr.jpg",
    },
    hr: {
      name: "Karen Zhang",
      title: "Technical Recruiter",
      photo: "/assets/hr/meta-hr.jpg",
      email: "recruiting@meta.com",
    },
    tags: ["PHP", "Hack", "C++", "Python", "React"],
    description:
      "About the Role: Meta is seeking Software Engineers to join our product and infrastructure teams. You'll work on applications serving billions of people and systems operating at unprecedented scale.\n\nWhat You'll Do: Develop full-stack web or mobile applications. Build infrastructure that scales to handle massive amounts of data. Work with Product Managers and Designers to build end-to-end experiences. Write clean, maintainable code and participate in design and code reviews.\n\nAbout Us: Meta builds technologies that help people connect, find communities, and grow businesses. Our products include Facebook, Instagram, WhatsApp, and Reality Labs.",
    requirements: [
      "BS/MS in Computer Science or related field",
      "Experience in PHP, Hack, C++, Python, React, or large-scale storage infrastructure",
      "Experience in object-oriented software development and multithreading programming",
      "In-person role at Menlo Park or Washington offices",
    ],
    benefits: [
      "Comprehensive medical, dental, and vision",
      "401(k) with company match",
      "Generous equity (RSUs)",
      "22 days PTO per year",
      "Free meals, transportation, and fitness programs",
    ],
    teamSize: "Varies — typically 6-15 per team",
    culture: ["Move fast", "Focus on impact", "Be open", "Build social value"],
  },
  {
    id: "10",
    company: "Amazon",
    role: "Software Development Engineer (SDE II)",
    location: "Seattle, WA",
    salary: "$151,000 - $236,500",
    manager: {
      name: "Werner Vogels",
      title: "CTO",
      tagline: "Everything fails, all the time. Design for that.",
      photo: "/assets/managers/amazon-mgr.jpg",
    },
    hr: {
      name: "Michelle Torres",
      title: "Technical Recruiter",
      photo: "/assets/hr/amazon-hr.jpg",
      email: "university-recruiting@amazon.com",
    },
    tags: ["Java", "AWS", "Distributed Systems", "Python", "DynamoDB"],
    description:
      "About the Role: As an SDE II at Amazon, you own technical design and implementation of complex features. You make critical decisions about technology, design, and coding standards. You mentor junior engineers and set direction for the team.\n\nWhat You'll Do: Design and develop scalable cloud-native solutions using microservices architecture. Build resilient, fault-tolerant distributed systems. Handle operational duties including on-call responsibilities. Demonstrate operational excellence through monitoring, troubleshooting, and resolving production issues.\n\nAbout Us: Amazon's mission is to be Earth's most customer-centric company. From e-commerce to AWS to Alexa, we're always looking to pioneer new technologies.",
    requirements: [
      "3+ years of non-internship professional software development experience",
      "2+ years of non-internship design or architecture experience",
      "Experience programming with at least one modern language (Java, C++, Python)",
      "Experience with distributed systems design and implementation",
      "BS in Computer Science or equivalent",
    ],
    benefits: [
      "Medical, dental, vision, and prescription insurance",
      "401(k) with company match",
      "Restricted Stock Units (RSUs)",
      "Paid time off and parental leave",
      "Sign-on bonus",
    ],
    teamSize: "Two-pizza teams (6-10 engineers)",
    culture: ["Customer obsession", "Ownership", "Bias for action", "Earn trust"],
  },
  {
    id: "11",
    company: "Amazon",
    role: "Software Development Engineer, 2026 (New Grad)",
    location: "Seattle, WA or Arlington, VA",
    salary: "$110,500 - $160,000",
    manager: {
      name: "Srikanth Thirumalai",
      title: "VP of Engineering",
      tagline: "Build technology that touches hundreds of millions of customers.",
      photo: "/assets/managers/amazon-mgr2.jpg",
    },
    hr: {
      name: "James Rodriguez",
      title: "University Recruiter",
      photo: "/assets/hr/amazon-hr2.jpg",
      email: "university-recruiting@amazon.com",
    },
    tags: ["Java", "Python", "C++", "Go", "Rust"],
    description:
      "About the Role: Amazon is hiring new grad Software Development Engineers who are passionate about solving customer problems through scalable technology. SDEs work on distributed systems impacting millions of customers globally, operating in an agile environment practicing CI/CD principles.\n\nWhat You'll Do: Design and develop scalable cloud-native solutions using microservices. Collaborate on cross-functional teams. Participate in code reviews and technical documentation. Leverage AI/GenAI development tools. Handle operational duties including on-call responsibilities.\n\nAbout Us: From Day 1, Amazon engineers are given real ownership. Your code ships to production and impacts customers immediately.",
    requirements: [
      "Currently enrolled or completed Bachelor's degree (or higher) in CS, CE, Data Science, or STEM",
      "Expected graduation between October 2025 - September 2026",
      "Proficiency in at least one programming language (Java, Python, C++, C#, Go, Rust, TypeScript)",
      "Experience with data structures, algorithms, or object-oriented design principles",
    ],
    benefits: [
      "Sign-on payments and restricted stock units (RSUs)",
      "Medical, dental, vision insurance",
      "401(k) matching",
      "Paid time off and parental leave",
      "Relocation assistance",
    ],
    teamSize: "Two-pizza teams (6-10 engineers)",
    culture: ["Day 1 mentality", "Customer obsession", "Dive deep", "Think big"],
  },
  {
    id: "12",
    company: "Apple",
    role: "Senior Software Engineer",
    location: "Cupertino, CA (On-site)",
    salary: "$175,800 - $312,200",
    manager: {
      name: "Craig Federighi",
      title: "SVP Software Engineering",
      tagline: "We make products that enrich people's lives.",
      photo: "/assets/managers/apple-mgr.jpg",
    },
    hr: {
      name: "Stephanie Lewis",
      title: "Talent Partner, Engineering",
      photo: "/assets/hr/apple-hr.jpg",
      email: "apple-jobs@apple.com",
    },
    tags: ["Swift", "Objective-C", "C++", "macOS", "iOS"],
    description:
      "About the Role: As a Senior Software Engineer at Apple, you'll contribute to the software that powers Apple products used by over a billion people worldwide. You'll work on projects that define and shape the future of computing.\n\nWhat You'll Do: Design and implement new features for Apple platforms. Collaborate with cross-functional teams including hardware, design, and QA. Optimize software for performance, reliability, and battery efficiency. Mentor other engineers and contribute to technical direction.\n\nAbout Us: Apple is the world's most valuable technology company, building hardware, software, and services that define the future of personal technology. From iPhone to Mac to Apple Vision Pro, we push the boundaries of what's possible.",
    requirements: [
      "5+ years of software development experience",
      "Strong proficiency in Swift, Objective-C, or C++",
      "Experience with Apple platforms (iOS, macOS, watchOS, or visionOS)",
      "Track record of shipping high-quality software to millions of users",
      "BS/MS in Computer Science or equivalent experience",
    ],
    benefits: [
      "RSU (Restricted Stock Unit) awards",
      "Annual cash bonus",
      "Comprehensive medical, dental, and vision",
      "Employee stock purchase plan (ESPP)",
      "Product discounts and education reimbursement",
    ],
    teamSize: "Varies by team — typically 8-20 engineers",
    culture: ["Secrecy and focus", "Attention to detail", "Cross-functional", "Ship quality"],
  },
  {
    id: "13",
    company: "Netflix",
    role: "Senior Software Engineer",
    location: "Los Gatos, CA or Remote (US)",
    salary: "$300,000 - $500,000",
    manager: {
      name: "Elizabeth Stone",
      title: "CTO",
      tagline: "Freedom and responsibility. That's how we build the best streaming platform.",
      photo: "/assets/managers/netflix-mgr.jpg",
    },
    hr: {
      name: "Daniel Osei",
      title: "Technical Recruiter",
      photo: "/assets/hr/netflix-hr.jpg",
      email: "recruiting@netflix.com",
    },
    tags: ["Java", "Python", "React", "GraphQL", "Microservices"],
    description:
      "About the Role: Every software engineer at Netflix is a senior engineer. We hire and compensate at the top of the market because we expect you to operate with full autonomy and judgment. You'll make architectural decisions that impact 300M+ subscribers.\n\nWhat You'll Do: Own end-to-end feature development from ideation to production. Build scalable microservices handling billions of API calls per day. Partner with product and design to shape the Netflix experience. Participate in architecture reviews and contribute to engineering culture.\n\nAbout Us: Netflix is the world's leading streaming entertainment service with 300M+ paid memberships across 190+ countries. We are a high-performance culture that values freedom and responsibility.",
    requirements: [
      "Strong experience with Java, Python, or similar backend languages",
      "Experience building and operating distributed systems at scale",
      "Track record of delivering high-quality software with minimal oversight",
      "Strong problem-solving skills and ability to work autonomously",
      "Experience with cloud infrastructure (AWS preferred)",
    ],
    benefits: [
      "Top-of-market salary (no annual bonuses — it's all in base)",
      "Unlimited PTO",
      "Stock option program",
      "Comprehensive health, dental, vision",
      "Generous parental leave",
    ],
    teamSize: "Varies — small autonomous teams",
    culture: ["Freedom and responsibility", "Context not control", "High performance", "Radical candor"],
  },
  {
    id: "14",
    company: "Coinbase",
    role: "Software Engineer, Backend (Institutional Markets)",
    location: "Remote (US)",
    salary: "$149,500 - $176,000",
    manager: {
      name: "Rohit Gupta",
      title: "VP of Engineering",
      tagline: "Building the future of the cryptoeconomy.",
      photo: "/assets/managers/coinbase-mgr.jpg",
    },
    hr: {
      name: "Sarah Williams",
      title: "Technical Recruiter",
      photo: "/assets/hr/coinbase-hr.jpg",
      email: "careers@coinbase.com",
    },
    tags: ["Go", "Ruby", "Python", "Blockchain", "Crypto"],
    description:
      "About the Role: Build the backend infrastructure powering Coinbase's institutional trading products — derivatives, spot trading, and custody solutions.\n\nWhat You'll Do: Design, build, scale and maintain production services. Collaborate with product and design teams to define and deliver new features. Write high-quality, well-tested code. Participate in on-call rotation and incident response.\n\nAbout Us: Coinbase is building the cryptoeconomy — a more fair, accessible, efficient, and transparent financial system enabled by crypto. We are a remote-first company trusted by millions of customers worldwide.",
    requirements: [
      "2+ years of experience in software engineering",
      "Proficiency in Go, Ruby, Python, or Java",
      "Experience designing, building, scaling and maintaining production services",
      "Knowledge of service-oriented architecture",
      "Familiarity with blockchain technology is a plus",
    ],
    benefits: [
      "Bonus eligibility + equity",
      "Medical, dental, vision and 401(k)",
      "Remote-first with periodic in-person events",
      "Home office stipend",
      "Crypto education resources and allowance",
    ],
    teamSize: "Institutional product team",
    culture: ["Remote-first", "Crypto-native", "Clear communication", "Efficient decision-making"],
  },
  {
    id: "15",
    company: "Coinbase",
    role: "Software Engineer, Data Platform",
    location: "Remote (US)",
    salary: "$147,900 - $174,000",
    manager: {
      name: "Varun Srinivasan",
      title: "Director of Engineering, Data",
      tagline: "Data infrastructure at the intersection of fintech and crypto.",
      photo: "/assets/managers/coinbase-mgr2.jpg",
    },
    hr: {
      name: "Emily Chung",
      title: "Recruiter",
      photo: "/assets/hr/coinbase-hr2.jpg",
      email: "careers@coinbase.com",
    },
    tags: ["Python", "Go", "Java", "Spark", "Data Pipelines"],
    description:
      "About the Role: Build and scale Coinbase's data platform infrastructure — the pipelines, systems, and tooling that power analytics, ML models, and compliance reporting across the company.\n\nWhat You'll Do: Design and build data pipelines at scale. Develop internal tooling for data discovery and governance. Ensure data quality and reliability for compliance-critical financial data. Partner with data scientists and analysts to enable self-service analytics.\n\nAbout Us: Coinbase serves millions of customers in over 100 countries. Our data platform processes billions of events per day from trading, custody, and blockchain systems.",
    requirements: [
      "2+ years of software engineering experience",
      "Strong Python, Go, or Java backend development skills",
      "General experience with data systems or pipelines",
      "Familiarity with cloud data services (AWS, GCP)",
      "Experience with Spark, Airflow, or similar data frameworks is a plus",
    ],
    benefits: [
      "Bonus eligibility + equity",
      "Medical, dental, vision and 401(k)",
      "Remote-first work culture",
      "Home office and internet stipend",
      "Annual learning and development budget",
    ],
    teamSize: "Data Platform team",
    culture: ["Remote-first", "Data-driven", "Mission-focused", "Clear communication"],
  },
  {
    id: "16",
    company: "Discord",
    role: "Senior Software Engineer, Frontend",
    location: "San Francisco, CA (Hybrid)",
    salary: "$196,000 - $220,500",
    manager: {
      name: "Jason Citron",
      title: "CEO & Co-Founder",
      tagline: "Imagine a place where you can belong to a school club, a gaming group, or a worldwide art community.",
      photo: "/assets/managers/discord-mgr.jpg",
    },
    hr: {
      name: "Nina Petrovic",
      title: "Senior Technical Recruiter",
      photo: "/assets/hr/discord-hr.jpg",
      email: "recruiting@discord.com",
    },
    tags: ["React", "TypeScript", "JavaScript", "Web", "Mobile"],
    description:
      "About the Role: Build consumer-facing products on web and mobile platforms for Discord's 200M+ monthly active users.\n\nWhat You'll Do: Design and implement new user-facing features. Build reusable components and libraries for future use. Optimize applications for maximum speed and scalability. Collaborate with design and product teams to define feature scope.\n\nAbout Us: Discord is the easiest way to talk over voice, video, and text. We've grown to over 200M monthly active users and are building a platform that powers communities of all sizes.",
    requirements: [
      "5+ years of experience as a Software Engineer",
      "Experience with React (preferred) and/or JavaScript",
      "Specialization in building consumer-facing products on web and mobile",
      "Domain expertise in either web or mobile front-end (or both)",
      "Strong problem-solving and communication skills",
    ],
    benefits: [
      "Equity compensation",
      "Comprehensive health benefits",
      "Flexible PTO",
      "Mental health and wellness programs",
      "Free Nitro subscription",
    ],
    teamSize: "Consumer product teams",
    culture: ["Community-first", "Move fast", "Play hard", "Inclusive"],
  },
  {
    id: "17",
    company: "Shopify",
    role: "Senior Developer",
    location: "Remote (US / Canada)",
    salary: "$158,000 - $218,000",
    manager: {
      name: "Farhan Thawar",
      title: "VP of Engineering",
      tagline: "Making commerce better for everyone.",
      photo: "/assets/managers/shopify-mgr.jpg",
    },
    hr: {
      name: "Andrea Williams",
      title: "Talent Partner",
      photo: "/assets/hr/shopify-hr.jpg",
      email: "careers@shopify.com",
    },
    tags: ["Ruby", "React", "TypeScript", "GraphQL", "E-commerce"],
    description:
      "About the Role: Build the commerce platform that powers millions of businesses worldwide. At Shopify, every developer works on real problems that affect real merchants, from one-person shops to enterprise brands.\n\nWhat You'll Do: Develop features for the Shopify platform using Ruby on Rails and React. Ship code to production multiple times per day. Collaborate with product and UX teams to build merchant-facing experiences. Debug and resolve production issues affecting merchant storefronts.\n\nAbout Us: Shopify is a leading global commerce company, providing trusted tools to start, grow, market, and manage a retail business of any size. We power millions of businesses in 175+ countries.",
    requirements: [
      "5+ years software engineering experience",
      "Experience with Ruby, Python, or similar backend languages",
      "Strong JavaScript/TypeScript and React skills",
      "Experience with GraphQL APIs",
      "Track record of shipping features to production",
    ],
    benefits: [
      "Equity (RSUs)",
      "Flexible work arrangements (Digital by Default)",
      "Health, dental, and vision benefits",
      "RRSP/401(k) matching",
      "Home office allowance and internet reimbursement",
    ],
    teamSize: "Varies by team",
    culture: ["Digital by default (remote-first)", "Merchant obsessed", "Ship fast", "Long-term thinking"],
  },
  {
    id: "18",
    company: "Uber",
    role: "Senior Software Engineer (L5a)",
    location: "San Francisco, CA (Hybrid)",
    salary: "$196,000 - $217,500",
    manager: {
      name: "Sundeep Gupta",
      title: "VP of Engineering, Platform",
      tagline: "We ignite opportunity by setting the world in motion.",
      photo: "/assets/managers/uber-mgr.jpg",
    },
    hr: {
      name: "Tom Bradley",
      title: "Technical Recruiter",
      photo: "/assets/hr/uber-hr.jpg",
      email: "recruiting@uber.com",
    },
    tags: ["Java", "Go", "Python", "Distributed Systems", "Rides"],
    description:
      "About the Role: Build the systems that power rides, deliveries, and freight for hundreds of millions of users and drivers worldwide.\n\nWhat You'll Do: Design and build distributed backend systems handling millions of concurrent users. Lead technical design and implementation of large features. Mentor junior engineers and set engineering standards. On-call for services you own.\n\nAbout Us: Uber's platform connects millions of riders and drivers, serves food delivery through Uber Eats, and powers freight logistics. We operate in 10,000+ cities across 70+ countries.",
    requirements: [
      "5+ years of software engineering experience",
      "Strong proficiency in Java, Go, Python, or C++",
      "Experience designing and building distributed systems",
      "BS or MS in Computer Science or Engineering",
      "In-depth knowledge of data structures and algorithms",
    ],
    benefits: [
      "Equity (RSUs) with annual refresh",
      "Annual performance bonuses",
      "Comprehensive medical, dental, vision",
      "401(k) plan",
      "Uber credits and employee perks",
    ],
    teamSize: "Varies — typically 6-12 per team",
    culture: ["We build globally, we live locally", "Do the right thing", "Act like an owner", "Celebrate differences"],
  },
  {
    id: "19",
    company: "OpenAI",
    role: "Software Engineer",
    location: "San Francisco, CA (On-site)",
    salary: "$245,000 - $385,000",
    manager: {
      name: "Sam Altman",
      title: "CEO",
      tagline: "Building safe and beneficial AGI.",
      photo: "/assets/managers/openai-mgr.jpg",
    },
    hr: {
      name: "Diana Kowalski",
      title: "Technical Talent Partner",
      photo: "/assets/hr/openai-hr.jpg",
      email: "careers@openai.com",
    },
    tags: ["Python", "Kubernetes", "ML Infrastructure", "APIs", "AI"],
    description:
      "About the Role: Build the infrastructure and products that bring AI to billions of people. As a Software Engineer at OpenAI, you'll work on the APIs, infrastructure, and applications powering ChatGPT and the OpenAI platform.\n\nWhat You'll Do: Design and build scalable API infrastructure serving millions of developers. Develop the systems that train, serve, and monitor large language models. Work on ChatGPT product features and developer platform tools. Ship quickly and iterate based on user feedback.\n\nAbout Us: OpenAI's mission is to ensure that artificial general intelligence benefits all of humanity. We build and deploy the most advanced AI systems in the world, including GPT-4, DALL-E, and ChatGPT.",
    requirements: [
      "Strong software engineering skills with Python or similar languages",
      "Experience building distributed systems at scale",
      "Familiarity with ML infrastructure, model serving, or GPU computing",
      "Ability to work in a fast-paced, rapidly changing environment",
      "BS/MS in Computer Science or equivalent experience",
    ],
    benefits: [
      "Competitive salary + significant equity (Profit Participation Units)",
      "Comprehensive health, dental, vision",
      "401(k) plan",
      "Generous parental leave",
      "Free meals and commuter benefits",
    ],
    teamSize: "Varies — fast-growing org",
    culture: ["Mission-driven", "Move fast", "Safety-first", "Intellectually rigorous"],
  },
  {
    id: "20",
    company: "Databricks",
    role: "Staff Software Engineer",
    location: "San Francisco, CA or Remote (US)",
    salary: "$214,000 - $369,000",
    manager: {
      name: "Ali Ghodsi",
      title: "CEO & Co-Founder",
      tagline: "We're democratizing data and AI.",
      photo: "/assets/managers/databricks-mgr.jpg",
    },
    hr: {
      name: "Grace Adeyemi",
      title: "Engineering Recruiter",
      photo: "/assets/hr/databricks-hr.jpg",
      email: "careers@databricks.com",
    },
    tags: ["Scala", "Python", "Spark", "Delta Lake", "ML Platform"],
    description:
      "About the Role: Lead the design and delivery of industry-leading data and AI systems as a Staff Engineer at Databricks.\n\nWhat You'll Do: Drive technical direction for critical platform components. Build systems that process petabytes of data for thousands of enterprise customers. Mentor and grow engineers across the organization. Shape engineering culture and practices.\n\nAbout Us: Databricks invented the Data Lakehouse. Our platform unifies data engineering, data science, and machine learning. We serve over 10,000 organizations worldwide, including more than 60% of the Fortune 500.",
    requirements: [
      "8+ years of software engineering experience",
      "Led the design and delivery of complex systems at scale",
      "Unique depth of technical expertise across engineering organization",
      "Experience leveraging AI tools to enhance development",
      "Strong skills in Scala, Python, Go, or similar languages",
    ],
    benefits: [
      "Healthcare, dental, and mental health coverage",
      "401(k) plan with employer match",
      "Equity compensation",
      "Paid time off and fitness reimbursements",
      "Discounted employee stock purchase plan",
    ],
    teamSize: "Platform engineering",
    culture: ["Open source roots", "Data-obsessed", "Customer-driven", "AI-first development"],
  },
  {
    id: "21",
    company: "Ramp",
    role: "Software Engineer",
    location: "New York, NY (Hybrid)",
    salary: "$164,000 - $220,000",
    manager: {
      name: "Karim Atiyeh",
      title: "CTO & Co-Founder",
      tagline: "We're building the financial automation platform every business deserves.",
      photo: "/assets/managers/ramp-mgr.jpg",
    },
    hr: {
      name: "Amanda Liu",
      title: "Engineering Recruiter",
      photo: "/assets/hr/ramp-hr.jpg",
      email: "careers@ramp.com",
    },
    tags: ["Python", "TypeScript", "Go", "AWS", "Fintech"],
    description:
      "About the Role: Build financial automation products that help businesses save time and money. Ramp is the fastest-growing corporate card and expense management platform in America.\n\nWhat You'll Do: Build full-stack features across our card, expense management, and bill pay products. Design and implement APIs and distributed backend services. Collaborate with product, design, and data science teams. Ship quickly in a fast-paced, high-ownership environment.\n\nAbout Us: Ramp is the financial operations platform designed to save businesses time and money. We're valued at $7.65B, growing rapidly, and backed by top investors. Our customers include Shopify, Airbnb, and thousands of businesses of all sizes.",
    requirements: [
      "Strong proficiency in Python, Go, or TypeScript",
      "Experience with distributed systems and APIs",
      "Familiarity with cloud platforms (AWS or GCP)",
      "CI/CD tools and version control (Git)",
      "Strong problem-solving skills and collaborative mindset",
    ],
    benefits: [
      "Competitive equity compensation",
      "Comprehensive health, dental, vision",
      "401(k) plan",
      "Hybrid work flexibility",
      "Generous PTO and parental leave",
    ],
    teamSize: "Product engineering teams",
    culture: ["Speed of execution", "High ownership", "No bureaucracy", "Customer-obsessed"],
  },
  {
    id: "22",
    company: "Palantir",
    role: "Software Engineer",
    location: "New York, NY or Washington, DC",
    salary: "$135,000 - $205,000",
    manager: {
      name: "Shyam Sankar",
      title: "CTO",
      tagline: "We build software that empowers organizations to effectively integrate their data.",
      photo: "/assets/managers/palantir-mgr.jpg",
    },
    hr: {
      name: "Patrick Sullivan",
      title: "Technical Recruiter",
      photo: "/assets/hr/palantir-hr.jpg",
      email: "recruiting@palantir.com",
    },
    tags: ["Java", "Python", "C++", "Distributed Systems", "Government"],
    description:
      "About the Role: Build software platforms that solve the world's hardest problems. Palantir's software is used by governments and enterprises to make sense of complex, distributed data.\n\nWhat You'll Do: Design and implement features for Foundry or Gotham platforms. Work closely with deployment teams and end-users to understand real-world problems. Build scalable, reliable backend systems. Contribute to platform architecture and direction.\n\nAbout Us: Palantir builds the world's leading data integration and analysis platforms. Our products — Foundry, Gotham, and AIP — are used by governments, militaries, and enterprises across 40+ countries.",
    requirements: [
      "Strong programming skills in Java, Python, or C++",
      "Solid understanding of algorithms, data structures, and system design",
      "BS/MS in Computer Science or Engineering",
      "Familiarity with distributed systems and cloud platforms",
      "Active or ability to obtain US security clearance preferred",
    ],
    benefits: [
      "Equity (RSUs)",
      "Comprehensive health, dental, and vision",
      "401(k) plan",
      "Relocation assistance",
      "Professional development budget",
    ],
    teamSize: "Forward-deployed or platform teams (4-8 engineers)",
    culture: ["Mission-driven", "High intellectual rigor", "Forward-deployed", "Work on hard problems"],
  },
  {
    id: "23",
    company: "Spotify",
    role: "Backend Engineer",
    location: "New York, NY or Stockholm, Sweden",
    salary: "$140,000 - $205,000",
    manager: {
      name: "Tyson Singer",
      title: "VP of Engineering, Personalization",
      tagline: "Audio is our canvas. Technology is our brush.",
      photo: "/assets/managers/spotify-mgr.jpg",
    },
    hr: {
      name: "Samira Patel",
      title: "Technical Recruiter",
      photo: "/assets/hr/spotify-hr.jpg",
      email: "recruiting@spotify.com",
    },
    tags: ["Java", "Python", "GCP", "Microservices", "Streaming"],
    description:
      "About the Role: Build the backend infrastructure that powers music and podcast discovery for 600M+ users. Join one of the autonomous engineering squads that define Spotify's product experience.\n\nWhat You'll Do: Design and build microservices powering personalization and content delivery. Operate services at massive scale on GCP. Collaborate with data scientists on recommendation systems. Participate in squad-level planning and architecture decisions.\n\nAbout Us: Spotify is the world's most popular audio streaming subscription service with 600M+ users, including 240M+ subscribers, across 184 markets. Our engineering culture is built around autonomous squads, chapters, tribes, and guilds.",
    requirements: [
      "3+ years of backend engineering experience",
      "Strong Java or Python skills",
      "Experience building and operating microservices at scale",
      "Familiarity with cloud platforms (GCP or AWS)",
      "Experience with data processing systems is a plus",
    ],
    benefits: [
      "Equity compensation",
      "Comprehensive healthcare",
      "Flexible public holidays and generous PTO",
      "Parental leave (6 months)",
      "Free Spotify Premium",
    ],
    teamSize: "Autonomous squads (5-9 engineers)",
    culture: ["Band, not an army", "Think it, build it, ship it, tweak it", "Autonomous squads", "Inclusive"],
  },
  {
    id: "24",
    company: "Figma",
    role: "Software Engineer",
    location: "San Francisco, CA (Hybrid)",
    salary: "$149,000 - $350,000",
    manager: {
      name: "Kris Raghavan",
      title: "VP of Engineering",
      tagline: "Nothing great is made alone. We're building the tools that prove it.",
      photo: "/assets/managers/figma-mgr.jpg",
    },
    hr: {
      name: "Emily Santos",
      title: "Engineering Recruiter",
      photo: "/assets/hr/figma-hr.jpg",
      email: "careers@figma.com",
    },
    tags: ["TypeScript", "C++", "WebAssembly", "React", "Collaboration"],
    description:
      "About the Role: Build the collaborative design platform used by millions of designers and developers worldwide. Figma runs entirely in the browser using a custom C++/WebAssembly rendering engine.\n\nWhat You'll Do: Develop features for Figma's design editor, FigJam, or Dev Mode. Work on real-time collaboration infrastructure. Build performant UI using TypeScript and React. Optimize the WebAssembly rendering engine for complex documents.\n\nAbout Us: Figma is the leading collaborative design platform. Born on the web, Figma helps entire product teams brainstorm, design, and build better products. We're used by companies like Microsoft, Uber, and Netflix.",
    requirements: [
      "Strong foundation in computer science fundamentals",
      "Experience with TypeScript/JavaScript or C++",
      "Interest in building creative tools and developer platforms",
      "Experience with web technologies and browser APIs",
      "Track record of shipping high-quality software",
    ],
    benefits: [
      "Equity compensation",
      "Comprehensive health, dental, and vision",
      "401(k) plan",
      "Flexible PTO and parental leave",
      "Work-from-home stipend",
    ],
    teamSize: "Product teams (5-10 engineers)",
    culture: ["Collaborative by nature", "Build for builders", "Grow as you go", "Make space for play"],
  },
  {
    id: "25",
    company: "LinkedIn",
    role: "Software Engineer",
    location: "Sunnyvale, CA (Hybrid)",
    salary: "$128,000 - $212,000",
    manager: {
      name: "Mohak Shroff",
      title: "SVP of Engineering",
      tagline: "Connect the world's professionals to make them more productive and successful.",
      photo: "/assets/managers/linkedin-mgr.jpg",
    },
    hr: {
      name: "Marcus Johnson",
      title: "Technical Recruiter",
      photo: "/assets/hr/linkedin-hr.jpg",
      email: "recruiting@linkedin.com",
    },
    tags: ["Java", "React", "Kafka", "Ember.js", "REST APIs"],
    description:
      "About the Role: Build products and features that help 1B+ professionals worldwide connect, learn, and grow their careers. LinkedIn engineers work on search, feed, messaging, ads, and enterprise products.\n\nWhat You'll Do: Design and build server-side applications in Java. Develop responsive web interfaces with React or Ember.js. Build and consume REST APIs and event-driven systems (Kafka). Ship features to production through CI/CD pipelines.\n\nAbout Us: LinkedIn is the world's largest professional network with 1B+ members in 200+ countries. As part of Microsoft, we offer the stability of a large company with the innovation of a tech startup.",
    requirements: [
      "BS/MS in Computer Science or related field",
      "Experience with object-oriented programming (Java, C++, or Python)",
      "Understanding of web technologies, RESTful APIs, and databases",
      "Experience with large-scale distributed systems",
      "Strong problem-solving and communication skills",
    ],
    benefits: [
      "Unlimited PTO and sick days",
      "Free meals five days a week",
      "$2,000/year wellness stipend",
      "100% donation matching up to $15,000",
      "Comprehensive health, dental, and vision",
    ],
    teamSize: "Varies — typically 6-12 per team",
    culture: ["Members first", "Relationships matter", "Be open, honest and constructive", "Act like an owner"],
  },
  {
    id: "26",
    company: "Airbnb",
    role: "Software Engineer, Backend",
    location: "San Francisco, CA (Hybrid)",
    salary: "$185,000 - $265,000",
    manager: {
      name: "Dave Stephenson",
      title: "CFO & Head of Engineering",
      tagline: "Belong anywhere.",
      photo: "/assets/managers/airbnb-mgr.jpg",
    },
    hr: {
      name: "Hannah Liu",
      title: "Engineering Talent Partner",
      photo: "/assets/hr/airbnb-hr.jpg",
      email: "careers@airbnb.com",
    },
    tags: ["Java", "Ruby", "Kubernetes", "React", "Payments"],
    description:
      "About the Role: Build the platform that powers 7M+ active listings and connects millions of guests with hosts worldwide.\n\nWhat You'll Do: Design and build scalable services for search, booking, payments, or host tools. Work on service-oriented architecture handling millions of requests per second. Collaborate with cross-functional teams including product, design, and data science. Own systems end-to-end from design through production.\n\nAbout Us: Airbnb is a community-based platform for listing, discovering, and booking accommodations around the world. We've hosted over 2 billion guest arrivals across 220+ countries.",
    requirements: [
      "3+ years of industry experience in software engineering",
      "Strong proficiency in Java, Ruby, Go, or similar backend languages",
      "Experience building microservices and distributed systems",
      "Understanding of relational databases and caching strategies",
      "BS/MS in Computer Science or equivalent",
    ],
    benefits: [
      "Equity (RSUs) with annual refresh",
      "Comprehensive medical, dental, and vision",
      "401(k) plan",
      "$2,000 annual Airbnb travel credit",
      "Quarterly hackathons and employee resource groups",
    ],
    teamSize: "Varies — product and infrastructure teams",
    culture: ["Belong anywhere", "Be a host", "Champion the mission", "Every frame matters"],
  },
  {
    id: "27",
    company: "Cloudflare",
    role: "Systems Engineer",
    location: "Austin, TX or San Francisco, CA",
    salary: "$140,000 - $204,000",
    manager: {
      name: "John Graham-Cumming",
      title: "CTO",
      tagline: "We're helping build a better Internet.",
      photo: "/assets/managers/cloudflare-mgr.jpg",
    },
    hr: {
      name: "Nina Petrovic",
      title: "Technical Recruiter",
      photo: "/assets/hr/cloudflare-hr.jpg",
      email: "recruiting@cloudflare.com",
    },
    tags: ["Rust", "Go", "Linux", "Networking", "Edge Computing"],
    description:
      "About the Role: Build and operate the network that powers ~20% of the web. Cloudflare's network spans 300+ cities and handles trillions of requests per month.\n\nWhat You'll Do: Design and implement high-performance network services in Rust and Go. Optimize Linux kernel networking performance. Build DDoS mitigation and WAF (Web Application Firewall) systems. Operate distributed systems across 300+ points of presence worldwide.\n\nAbout Us: Cloudflare is on a mission to help build a better Internet. Our network protects and accelerates millions of Internet properties. We serve ~20% of all web traffic.",
    requirements: [
      "Experience with Rust, Go, C, or C++",
      "Strong understanding of Linux systems programming and networking",
      "Familiarity with HTTP, DNS, TLS, and TCP/UDP protocols",
      "Experience with distributed systems at scale",
      "Interest in network security and performance",
    ],
    benefits: [
      "Equity compensation",
      "Comprehensive health insurance",
      "401(k) plan",
      "Flexible PTO",
      "Internet reimbursement",
    ],
    teamSize: "Systems teams (5-10 engineers)",
    culture: ["Help build a better internet", "Curiosity-driven", "Open and transparent", "Ship and iterate"],
  },
  {
    id: "28",
    company: "Notion",
    role: "Software Engineer",
    location: "San Francisco, CA or New York, NY",
    salary: "$170,000 - $270,000",
    manager: {
      name: "Simon Last",
      title: "Co-Founder & CTO",
      tagline: "We're on a mission to make toolmaking ubiquitous.",
      photo: "/assets/managers/notion-mgr.jpg",
    },
    hr: {
      name: "Ryan Foster",
      title: "Engineering Recruiter",
      photo: "/assets/hr/notion-hr.jpg",
      email: "careers@makenotion.com",
    },
    tags: ["TypeScript", "React", "Kotlin", "PostgreSQL", "AI"],
    description:
      "About the Role: Build the connected workspace that millions of people and teams use to write, plan, and get organized. Notion is a single tool that replaces docs, wikis, project management, and more.\n\nWhat You'll Do: Build new features for the Notion editor, databases, AI, or collaboration systems. Design APIs and backend services in Kotlin/JVM. Develop the real-time collaboration engine. Ship rapidly with a small, high-impact team.\n\nAbout Us: Notion is the connected workspace where better, faster work happens. Used by teams at companies like Nike, Toyota, Figma, and Pixar. We're building the tools that power how the world organizes its knowledge.",
    requirements: [
      "Strong fundamentals in computer science and software engineering",
      "Experience with TypeScript, React, or modern frontend frameworks",
      "Backend experience with Kotlin, Java, or similar JVM languages",
      "Experience with PostgreSQL or similar databases",
      "Passion for building productivity tools",
    ],
    benefits: [
      "Equity compensation",
      "Comprehensive health, dental, and vision",
      "Flexible PTO",
      "Wellness and learning stipends",
      "Commuter benefits",
    ],
    teamSize: "Small teams (3-6 engineers)",
    culture: ["Mission-driven", "Craft-obsessed", "Humble ambition", "Move deliberately"],
  },
  {
    id: "29",
    company: "Block (Square)",
    role: "Senior Software Engineer",
    location: "San Francisco, CA or Remote (US)",
    salary: "$198,000 - $297,000",
    manager: {
      name: "Dhanji R. Prasanna",
      title: "CTO",
      tagline: "Economic empowerment is the purpose. Technology is the means.",
      photo: "/assets/managers/block-mgr.jpg",
    },
    hr: {
      name: "Catherine Bell",
      title: "Technical Recruiter",
      photo: "/assets/hr/block-hr.jpg",
      email: "careers@squareup.com",
    },
    tags: ["Java", "Kotlin", "Ruby", "AWS", "Payments"],
    description:
      "About the Role: Build the commerce and financial tools that help millions of sellers run and grow their businesses. Square's platform processes billions of dollars in payments each year.\n\nWhat You'll Do: Design and implement payment processing systems at scale. Build merchant-facing tools for inventory, invoicing, and banking. Develop APIs consumed by third-party developers. Mentor engineers and contribute to technical strategy.\n\nAbout Us: Block (formerly Square) builds tools to empower sellers, help them run their businesses, and reach more buyers. From Square POS to Cash App to TIDAL, we're purpose-built around economic empowerment.",
    requirements: [
      "5+ years of software engineering experience",
      "Strong proficiency in Java, Kotlin, Ruby, or Go",
      "Experience building distributed systems and APIs at scale",
      "Understanding of payment systems, billing, or financial software",
      "BS/MS in Computer Science or equivalent",
    ],
    benefits: [
      "Equity (RSUs)",
      "Comprehensive health, dental, and vision",
      "401(k) plan with company match",
      "Flexible work arrangements (remote-friendly)",
      "Learning and development stipend",
    ],
    teamSize: "Product teams (6-12 engineers)",
    culture: ["Purpose-driven", "Move fast and fix things", "Transparent", "Diverse and inclusive"],
  },
  {
    id: "30",
    company: "Anthropic",
    role: "Software Engineer",
    location: "San Francisco, CA (Hybrid)",
    salary: "$250,000 - $375,000",
    manager: {
      name: "Dario Amodei",
      title: "CEO & Co-Founder",
      tagline: "Building reliable, interpretable, and steerable AI systems.",
      photo: "/assets/managers/anthropic-mgr.jpg",
    },
    hr: {
      name: "Kevin Choi",
      title: "Engineering Talent Partner",
      photo: "/assets/hr/anthropic-hr.jpg",
      email: "careers@anthropic.com",
    },
    tags: ["Python", "Rust", "Kubernetes", "ML Infrastructure", "AI Safety"],
    description:
      "About the Role: Build the infrastructure and products that make AI safe and beneficial. Work on the systems behind Claude, our AI assistant.\n\nWhat You'll Do: Build scalable serving infrastructure for large language models. Develop the APIs and developer platform powering Claude integrations. Work on evaluation and safety tooling for AI systems. Contribute to product features for claude.ai and the Claude API.\n\nAbout Us: Anthropic is an AI safety company that builds reliable, interpretable, and steerable AI systems. We created Claude, one of the world's leading AI assistants. Our mission is the responsible development and maintenance of advanced AI for the long-term benefit of humanity.",
    requirements: [
      "Strong software engineering skills with Python, Rust, or Go",
      "Experience with distributed systems and cloud infrastructure (AWS/GCP)",
      "Familiarity with ML infrastructure, model serving, or large-scale systems",
      "Strong problem-solving and systems design abilities",
      "BS/MS in Computer Science or equivalent experience",
    ],
    benefits: [
      "Significant equity compensation",
      "Comprehensive health, dental, and vision",
      "401(k) plan",
      "Generous parental leave",
      "Free meals and commuter benefits",
    ],
    teamSize: "Varies — rapidly growing engineering org",
    culture: ["Safety-first", "Intellectually rigorous", "Mission-driven", "Collaborative"],
  },
];
