options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_API_KEY: ""
  _FIREBASE_AUTH_DOMAIN: ""
  _FIREBASE_PROJECT_ID: "clawjob"
  _FIREBASE_STORAGE_BUCKET: ""
  _FIREBASE_MESSAGING_SENDER_ID: ""
  _FIREBASE_APP_ID: ""
  _ADMIN_EMAILS: ""
  _RAPIDAPI_KEY: ""
  _ADZUNA_APP_ID: ""
  _ADZUNA_API_KEY: ""
  _REED_API_KEY: ""
  _PROXYCURL_API_KEY: ""
  _HUNTER_API_KEY: ""
  _GENERATED_PHOTOS_API_KEY: ""

steps:
  # Build Docker image with Firebase env vars from substitutions
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:latest'
      - '.'

  # Push commit SHA tagged image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:$COMMIT_SHA'

  # Push latest tagged image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'clawjob'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},ADMIN_EMAILS=${_ADMIN_EMAILS},RAPIDAPI_KEY=${_RAPIDAPI_KEY},ADZUNA_APP_ID=${_ADZUNA_APP_ID},ADZUNA_API_KEY=${_ADZUNA_API_KEY},REED_API_KEY=${_REED_API_KEY},PROXYCURL_API_KEY=${_PROXYCURL_API_KEY},HUNTER_API_KEY=${_HUNTER_API_KEY},GENERATED_PHOTOS_API_KEY=${_GENERATED_PHOTOS_API_KEY}'

images:
  - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/${_FIREBASE_PROJECT_ID}/clawjob/clawjob:latest'
