import { initializeApp, applicationDefault, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";

if (getApps().length === 0) {
  initializeApp({
    credential: applicationDefault(),
    projectId: "clawjob",
  });
}

const db = getFirestore();

interface SeedJob {
  company: string;
  role: string;
  location: string;
  salary: string;
  manager: { name: string; title: string; tagline: string; photo: string; video?: string };
  hr: { name: string; title: string; photo: string; email: string; phone?: string };
  tags: string[];
  description: string;
  requirements: string[];
  benefits: string[];
  companyLogo: string;
  teamSize: string;
  culture: string[];
}

const jobs: SeedJob[] = [
  {
    company: "Meridian Health Systems",
    role: "Senior Software Engineer",
    location: "Remote",
    salary: "$155,000 - $205,000",
    manager: {
      name: "Dr. Anita Kapoor",
      title: "VP of Engineering",
      tagline: "We're building the infrastructure that makes healthcare accessible to everyone",
      photo: "/assets/managers/anita.jpg",
    },
    hr: {
      name: "Brian Costello",
      title: "Senior Technical Recruiter",
      photo: "/assets/hr/brian.jpg",
      email: "brian.costello@meridianhealth.io",
      phone: "(617) 555-0142",
    },
    tags: ["React", "TypeScript", "Node.js", "AWS", "HIPAA"],
    description:
      "About Us: Meridian Health Systems is a Series C healthtech company transforming how patients interact with their care providers through intuitive digital tools.\n\nAbout the Role: We're looking for a Senior Software Engineer to join our Patient Experience team. You'll own critical features across our telehealth platform used by 3M+ patients monthly.\n\nWhat You'll Do: Design and build full-stack features in React and Node.js, architect scalable microservices on AWS, mentor junior engineers, and collaborate with clinical teams to ship HIPAA-compliant software.",
    requirements: [
      "5+ years of professional software engineering experience",
      "Strong proficiency with React, TypeScript, and Node.js",
      "Experience building and deploying services on AWS (ECS, Lambda, RDS)",
      "Familiarity with healthcare data standards (HL7, FHIR) is a plus",
      "BS in Computer Science or equivalent practical experience",
    ],
    benefits: [
      "Comprehensive health, dental & vision (100% employee premium covered)",
      "401(k) with 4% company match",
      "Unlimited PTO with 15-day minimum",
      "Equity package with 4-year vesting",
      "$2,500 annual learning & development budget",
    ],
    companyLogo: "/assets/logos/meridian-health.png",
    teamSize: "14 engineers",
    culture: ["Remote-first", "Async communication", "Mission-driven", "Blameless postmortems"],
  },
  {
    company: "Apex Cloud Technologies",
    role: "Staff Frontend Engineer",
    location: "Hybrid — San Francisco, CA",
    salary: "$190,000 - $260,000",
    manager: {
      name: "Marcus Chen",
      title: "Director of Frontend Engineering",
      tagline: "We ship developer tools that make cloud infrastructure feel simple",
      photo: "/assets/managers/marcus.jpg",
      video: "/assets/managers/marcus-intro.mp4",
    },
    hr: {
      name: "Sarah Kim",
      title: "Engineering Talent Partner",
      photo: "/assets/hr/sarah.jpg",
      email: "sarah.kim@apexcloud.dev",
      phone: "(415) 555-0218",
    },
    tags: ["React", "TypeScript", "GraphQL", "Design Systems", "Series D"],
    description:
      "About the Role: Apex Cloud is hiring a Staff Frontend Engineer to lead the architecture of our cloud management console used by 10,000+ engineering teams worldwide.\n\nWhat You'll Do: Own the frontend platform layer including our design system, state management patterns, and build tooling. Drive technical decisions across 4 frontend squads. Partner with product design to define interaction patterns for complex infrastructure workflows.",
    requirements: [
      "8+ years of frontend engineering experience with React and TypeScript",
      "Track record of building and maintaining design systems at scale",
      "Experience with GraphQL, client-side caching (Apollo/Relay), and performance optimization",
      "Strong technical leadership skills — code reviews, RFCs, mentoring",
      "Experience working on developer tools or infrastructure products is a strong plus",
    ],
    benefits: [
      "Top-of-market compensation with annual equity refresh",
      "Hybrid schedule: 2 days in SF office, flexible otherwise",
      "$5,000 annual learning stipend",
      "Premium health, dental, vision + HSA contribution",
      "16 weeks paid parental leave",
    ],
    companyLogo: "/assets/logos/apex-cloud.png",
    teamSize: "32 frontend engineers across 4 squads",
    culture: ["Engineering-led", "Ship weekly", "Flat hierarchy", "Open source contributors"],
  },
  {
    company: "NovaPay Financial",
    role: "Backend Engineer II",
    location: "New York, NY (On-site)",
    salary: "$150,000 - $195,000",
    manager: {
      name: "Rachel Nguyen",
      title: "Engineering Manager, Payments",
      tagline: "Real-time payments, real impact. Millions of transactions daily",
      photo: "/assets/managers/rachel.jpg",
      video: "/assets/managers/rachel-intro.mp4",
    },
    hr: {
      name: "Tom Bradley",
      title: "Recruitment Lead",
      photo: "/assets/hr/tom.jpg",
      email: "tom.bradley@novapay.com",
      phone: "(212) 555-0167",
    },
    tags: ["Go", "PostgreSQL", "Kafka", "Fintech", "On-Site"],
    description:
      "About the Role: Join our Payments Infrastructure team to build the high-throughput transaction engine processing $2B+ in monthly volume.\n\nWhat You'll Do: Design and implement low-latency Go services handling real-time payment processing. Build event-driven pipelines with Kafka for transaction reconciliation. Collaborate with compliance to maintain PCI DSS standards.",
    requirements: [
      "3-5 years of backend development with Go, Java, or similar",
      "Strong experience with PostgreSQL and database optimization",
      "Knowledge of event-driven architectures (Kafka, RabbitMQ, or similar)",
      "Understanding of financial regulations and PCI compliance",
      "Experience with observability tools (Datadog, Grafana, or similar)",
    ],
    benefits: [
      "Competitive base + annual performance bonus (15-25%)",
      "401(k) with 5% match, vested immediately",
      "Commuter benefits and gym membership",
      "Generous RSU grants with 4-year vesting",
      "Catered lunches Monday through Friday",
    ],
    companyLogo: "/assets/logos/novapay.png",
    teamSize: "22 engineers",
    culture: ["High-performance", "Reliability-first", "Ownership mentality", "Rigorous code review"],
  },
  {
    company: "GreenGrid Energy",
    role: "ML/AI Engineer",
    location: "Remote",
    salary: "$175,000 - $245,000",
    manager: {
      name: "Priya Nair",
      title: "Head of AI & Analytics",
      tagline: "Using machine learning to accelerate the clean energy transition",
      photo: "/assets/managers/priya-n.jpg",
    },
    hr: {
      name: "Megan O'Brien",
      title: "People Operations Manager",
      photo: "/assets/hr/megan.jpg",
      email: "megan.obrien@greengrid.energy",
      phone: "(503) 555-1024",
    },
    tags: ["Python", "PyTorch", "Kubernetes", "GCP", "Climate Tech"],
    description:
      "About the Role: GreenGrid Energy is looking for an ML/AI Engineer to develop predictive models that optimize renewable energy grid operations.\n\nWhat You'll Do: Train and deploy ML models for solar/wind energy forecasting. Build real-time inference pipelines on GCP. Collaborate with power systems engineers to translate domain knowledge into features.",
    requirements: [
      "3+ years of ML engineering experience in production environments",
      "Proficiency with Python, PyTorch or TensorFlow, and scikit-learn",
      "Experience deploying models on Kubernetes or cloud ML platforms (Vertex AI, SageMaker)",
      "Strong background in time-series forecasting or signal processing",
      "MS or PhD in Computer Science, Statistics, or related field preferred",
    ],
    benefits: [
      "Mission-aligned 1% climate pledge bonus",
      "4-day work week (Fridays off)",
      "$5,000 annual conference and learning budget",
      "Comprehensive health, dental, vision + life insurance",
      "Sabbatical after 4 years of tenure",
    ],
    companyLogo: "/assets/logos/greengrid.png",
    teamSize: "10 ML engineers + data scientists",
    culture: ["Purpose-driven", "Research-oriented", "Sustainable", "Async-first"],
  },
  {
    company: "Tessera Analytics",
    role: "Data Platform Engineer",
    location: "Hybrid — Seattle, WA",
    salary: "$160,000 - $210,000",
    manager: {
      name: "Jordan Blake",
      title: "Head of Data Infrastructure",
      tagline: "We build the data backbone that powers every decision at Tessera",
      photo: "/assets/managers/jordan.jpg",
    },
    hr: {
      name: "Lisa Fernandez",
      title: "Technical Recruiter",
      photo: "/assets/hr/lisa.jpg",
      email: "lisa.fernandez@tessera.io",
      phone: "(206) 555-0892",
    },
    tags: ["Spark", "Airflow", "Snowflake", "dbt", "AWS"],
    description:
      "About the Role: We're hiring a Data Platform Engineer to own and scale our analytics infrastructure processing 50TB+ of event data daily.\n\nWhat You'll Do: Design and maintain ETL/ELT pipelines using Airflow and dbt. Optimize Snowflake warehouse performance and cost. Build data quality monitoring and alerting systems.",
    requirements: [
      "4+ years of data engineering experience",
      "Proficiency with Apache Spark, Airflow, or Dagster",
      "Experience with Snowflake, BigQuery, or Redshift",
      "Strong SQL and experience with dbt or similar transformation frameworks",
      "Familiarity with data quality tools (Great Expectations, Monte Carlo, or Soda)",
    ],
    benefits: [
      "Hybrid schedule: 3 days in Seattle office",
      "401(k) with 4% match",
      "$3,000 home office setup budget",
      "Comprehensive health insurance from day one",
      "Equity with standard 4-year vesting + 1-year cliff",
    ],
    companyLogo: "/assets/logos/tessera.png",
    teamSize: "8 data engineers",
    culture: ["Data-driven", "Pragmatic", "Collaborative", "Continuous improvement"],
  },
  {
    company: "Bastion Cyber",
    role: "Security Engineer",
    location: "Washington, DC (Hybrid)",
    salary: "$165,000 - $225,000",
    manager: {
      name: "Daniel Osei",
      title: "CISO",
      tagline: "Defending what matters most — our customers' trust",
      photo: "/assets/managers/daniel.jpg",
    },
    hr: {
      name: "Laura Mendez",
      title: "Talent Partner",
      photo: "/assets/hr/laura.jpg",
      email: "laura.mendez@bastioncyber.com",
      phone: "(202) 555-0672",
    },
    tags: ["AppSec", "Pen Testing", "Kubernetes", "Zero Trust"],
    description:
      "About the Role: Lead application security initiatives for our enterprise platform serving government and financial sector clients.\n\nWhat You'll Do: Conduct penetration testing and security code reviews. Build automated SAST/DAST pipelines in CI/CD. Implement zero-trust networking policies across our Kubernetes infrastructure.",
    requirements: [
      "5+ years in application or infrastructure security",
      "Experience with SAST/DAST tools and vulnerability management programs",
      "Proficiency in Python, Go, or Bash for security tooling",
      "Knowledge of container security and Kubernetes hardening",
      "OSCP, CEH, or equivalent certification preferred",
    ],
    benefits: [
      "Top-of-market compensation with annual refresh",
      "Security clearance sponsorship available",
      "Paid training and certification costs (unlimited)",
      "$4,000 annual security conference budget",
      "Flexible hybrid schedule (2 days in DC office)",
    ],
    companyLogo: "/assets/logos/bastion-cyber.png",
    teamSize: "9 security engineers",
    culture: ["Rigorous", "Trust-based", "Continuous learning", "Ethical hacking encouraged"],
  },
  {
    company: "Vantage Robotics",
    role: "Senior Full Stack Developer",
    location: "San Francisco, CA (On-site)",
    salary: "$170,000 - $220,000",
    manager: {
      name: "Alex Wu",
      title: "VP of Software Engineering",
      tagline: "Building the control layer for the next generation of autonomous systems",
      photo: "/assets/managers/alex-w.jpg",
    },
    hr: {
      name: "David Park",
      title: "Senior Recruiter",
      photo: "/assets/hr/david.jpg",
      email: "david.park@vantagerobotics.com",
      phone: "(415) 555-0291",
    },
    tags: ["React", "Python", "WebSockets", "Robotics", "Docker"],
    description:
      "About the Role: Join our Command & Control team to build real-time dashboards and APIs for autonomous drone fleet management.\n\nWhat You'll Do: Develop React-based operator interfaces with real-time telemetry visualization. Build Python backend services for mission planning and fleet coordination. Integrate WebSocket and gRPC streaming for low-latency communication with field hardware.",
    requirements: [
      "5+ years of full-stack development experience",
      "Strong React/TypeScript and Python skills",
      "Experience with real-time data systems (WebSockets, SSE, gRPC)",
      "Familiarity with Docker, CI/CD, and cloud infrastructure (AWS or GCP)",
      "Interest in robotics or hardware-software integration is a strong plus",
    ],
    benefits: [
      "Equity package with 4-year vesting and 1-year cliff",
      "Unlimited PTO with 3-week minimum",
      "$5,000 annual learning stipend",
      "On-site gym and catered lunches",
      "Relocation assistance up to $15,000",
    ],
    companyLogo: "/assets/logos/vantage-robotics.png",
    teamSize: "12 engineers",
    culture: ["Innovation-driven", "Hands-on", "Fast-paced", "Cross-functional"],
  },
  {
    company: "Stratos Cloud Platform",
    role: "DevOps Engineer",
    location: "Remote (US/EU)",
    salary: "$150,000 - $200,000",
    manager: {
      name: "Viktor Sokolov",
      title: "Director of Infrastructure",
      tagline: "Infrastructure so good, developers forget it exists",
      photo: "/assets/managers/viktor.jpg",
    },
    hr: {
      name: "Grace Adeyemi",
      title: "Global Recruiter",
      photo: "/assets/hr/grace.jpg",
      email: "grace.adeyemi@stratoscloud.dev",
      phone: "+1 (650) 555-0845",
    },
    tags: ["Terraform", "Kubernetes", "AWS", "GitHub Actions", "Linux"],
    description:
      "About the Role: Design and maintain the cloud infrastructure powering our multi-region SaaS platform with 99.99% uptime SLA.\n\nWhat You'll Do: Manage and optimize Kubernetes clusters across AWS regions. Build self-service developer tooling and golden-path templates. Implement infrastructure-as-code with Terraform. Own CI/CD pipelines and deployment automation.",
    requirements: [
      "4+ years in DevOps, SRE, or platform engineering",
      "Deep experience with Terraform, Pulumi, or CloudFormation",
      "Expertise managing production Kubernetes clusters (EKS, GKE, or AKS)",
      "Experience building CI/CD pipelines with GitHub Actions, GitLab CI, or Jenkins",
      "Strong Linux administration and networking fundamentals",
    ],
    benefits: [
      "Async-first culture with truly flexible hours",
      "Home internet and phone reimbursement",
      "Annual company summit (past: Lisbon, Kyoto, Vancouver)",
      "On-call compensation: $500/week + $200 per incident",
      "Generous equity refresh grants",
    ],
    companyLogo: "/assets/logos/stratos-cloud.png",
    teamSize: "7 platform engineers",
    culture: ["Async-first", "Engineering excellence", "Ownership", "Blameless postmortems"],
  },
  {
    company: "BrightPath Education",
    role: "Product Manager",
    location: "Chicago, IL (Hybrid)",
    salary: "$135,000 - $175,000",
    manager: {
      name: "Monica Li",
      title: "VP of Product",
      tagline: "Every student deserves a personalized learning path",
      photo: "/assets/managers/monica.jpg",
    },
    hr: {
      name: "Ryan Foster",
      title: "People & Culture Manager",
      photo: "/assets/hr/ryan.jpg",
      email: "ryan.foster@brightpath.edu",
      phone: "(312) 555-0789",
    },
    tags: ["Product Strategy", "A/B Testing", "EdTech", "Data Analysis"],
    description:
      "About the Role: Own the product roadmap for our adaptive learning platform used by 500+ school districts nationwide.\n\nWhat You'll Do: Define product strategy based on learning outcomes data. Run A/B experiments to optimize student engagement. Work closely with learning scientists, designers, and engineers.",
    requirements: [
      "4+ years of product management experience in consumer or EdTech",
      "Experience with A/B testing frameworks and data-informed decision making",
      "Comfort with SQL and analytics tools (Amplitude, Mixpanel, or Looker)",
      "Strong written and verbal communication skills",
      "Passion for education equity and student outcomes",
    ],
    benefits: [
      "Impact bonus tied to student outcome metrics",
      "Summer Fridays (half-day Fridays, June through August)",
      "$2,500 professional development budget",
      "Hybrid schedule: 3 days in Chicago office",
      "Comprehensive health, dental, vision insurance",
    ],
    companyLogo: "/assets/logos/brightpath.png",
    teamSize: "11 engineers, 3 designers, 2 data scientists",
    culture: ["Impact-first", "Learner-centered", "Collaborative", "Data-informed"],
  },
  {
    company: "Luminary AI",
    role: "Senior UX Designer",
    location: "San Francisco, CA (Hybrid)",
    salary: "$155,000 - $205,000",
    manager: {
      name: "Yuki Tanaka",
      title: "Head of Design",
      tagline: "Designing AI products that feel human",
      photo: "/assets/managers/yuki.jpg",
    },
    hr: {
      name: "Chris Tanaka",
      title: "Design & Research Recruiting Lead",
      photo: "/assets/hr/chris.jpg",
      email: "chris.tanaka@luminaryai.com",
      phone: "(415) 555-0912",
    },
    tags: ["Figma", "Design Systems", "AI/ML Products", "User Research"],
    description:
      "About the Role: Shape the user experience for Luminary's AI writing assistant used by 500K+ professionals daily.\n\nWhat You'll Do: Lead end-to-end design for key product surfaces. Conduct user research and usability testing. Build and maintain our design system in Figma. Partner with ML engineers to design intuitive interfaces for complex AI features.",
    requirements: [
      "5+ years of UX/product design experience",
      "Expert Figma skills including components, tokens, and prototyping",
      "Experience designing for AI/ML products or complex data-driven tools",
      "Strong portfolio demonstrating end-to-end design process",
      "Understanding of accessibility standards (WCAG 2.1 AA)",
    ],
    benefits: [
      "Competitive salary with signing bonus",
      "Latest MacBook Pro and design peripherals",
      "$3,000 annual design tools and conference budget",
      "Hybrid work: 2 days in SF office",
      "Comprehensive mental health coverage (therapy, coaching)",
    ],
    companyLogo: "/assets/logos/luminary-ai.png",
    teamSize: "8 designers",
    culture: ["Craft-obsessed", "User-first", "Research-driven", "Collaborative"],
  },
  {
    company: "Fireline Payments",
    role: "Engineering Manager",
    location: "New York, NY (Hybrid)",
    salary: "$195,000 - $270,000",
    manager: {
      name: "Olamide Adeyinka",
      title: "CTO",
      tagline: "Scale the team. Scale the system. Ship with confidence",
      photo: "/assets/managers/olamide.jpg",
    },
    hr: {
      name: "Catherine Bell",
      title: "VP of People",
      photo: "/assets/hr/catherine.jpg",
      email: "catherine.bell@firelinepay.com",
      phone: "(212) 555-1778",
    },
    tags: ["Leadership", "Distributed Systems", "Fintech", "Hiring"],
    description:
      "About the Role: Lead a team of 8 engineers building Fireline's real-time fraud detection and payment routing platform.\n\nWhat You'll Do: Manage and grow a high-performing engineering team. Make technical architecture decisions for systems handling $500M+ in daily volume. Partner with product and compliance to set roadmap priorities.",
    requirements: [
      "7+ years of software engineering experience",
      "2+ years of engineering management with direct reports",
      "Background in distributed systems, payments, or high-throughput platforms",
      "Track record of hiring, developing, and retaining strong engineers",
      "Strong written communication for RFCs, postmortems, and stakeholder updates",
    ],
    benefits: [
      "Staff-level equity grant with annual refresh",
      "Flexible hybrid arrangement (2-3 days in Manhattan office)",
      "$10,000 annual professional development budget",
      "Executive coaching included",
      "Premium health, dental, vision + 401(k) with 6% match",
    ],
    companyLogo: "/assets/logos/fireline.png",
    teamSize: "40+ engineers (you lead a pod of 8)",
    culture: ["Engineering-led", "High-bar hiring", "Autonomous teams", "Impact-oriented"],
  },
  {
    company: "Canopy Climate",
    role: "Cloud Architect",
    location: "Seattle, WA (Hybrid)",
    salary: "$180,000 - $250,000",
    manager: {
      name: "Viktor Sokolov",
      title: "VP of Technology",
      tagline: "Designing infrastructure for a sustainable future",
      photo: "/assets/managers/viktor.jpg",
    },
    hr: {
      name: "Tom Brennan",
      title: "HR Business Partner",
      photo: "/assets/hr/tom-b.jpg",
      email: "tom.brennan@canopyclimate.org",
      phone: "(206) 555-0421",
    },
    tags: ["AWS", "Terraform", "Kubernetes", "Multi-region", "Climate Tech"],
    description:
      "About the Role: Design and own the cloud architecture for Canopy's satellite data processing and ML inference platform.\n\nWhat You'll Do: Architect multi-region AWS infrastructure for petabyte-scale geospatial data processing. Design cost-optimized compute strategies for GPU-heavy ML training workloads. Implement security best practices and compliance controls.",
    requirements: [
      "7+ years of cloud infrastructure experience, including 3+ years in architecture roles",
      "Deep expertise with AWS services (EKS, S3, EMR, SageMaker, Step Functions)",
      "Strong Terraform/IaC skills and experience with GitOps workflows",
      "Experience with high-performance computing or large-scale data processing",
      "AWS Solutions Architect Professional or equivalent certification preferred",
    ],
    benefits: [
      "Carbon offset for your entire household",
      "4-day work week (Fridays off)",
      "Annual $5,000 conference and travel budget",
      "Comprehensive benefits with HSA contribution",
      "Sabbatical program after 4 years",
    ],
    companyLogo: "/assets/logos/canopy-climate.png",
    teamSize: "15 infrastructure + ML engineers",
    culture: ["Purpose-driven", "Technically ambitious", "Sustainable work practices", "Inclusive"],
  },
  {
    company: "ShopStream",
    role: "Mobile Engineer (iOS)",
    location: "Remote (US)",
    salary: "$145,000 - $195,000",
    manager: {
      name: "Diego Fernandez",
      title: "Mobile Team Lead",
      tagline: "Live shopping, reimagined for mobile-first experiences",
      photo: "/assets/managers/diego.jpg",
      video: "/assets/managers/diego-intro.mp4",
    },
    hr: {
      name: "Nina Petrovic",
      title: "Recruiter",
      photo: "/assets/hr/nina-p.jpg",
      email: "nina.petrovic@shopstream.io",
      phone: "(800) 555-0583",
    },
    tags: ["Swift", "SwiftUI", "AVFoundation", "E-commerce"],
    description:
      "About the Role: Build the iOS app for our live-commerce platform where creators sell products through real-time video.\n\nWhat You'll Do: Implement real-time video playback and in-stream purchasing flows. Build SwiftUI interfaces for product discovery and checkout. Optimize app performance for smooth streaming on older devices.",
    requirements: [
      "4+ years of native iOS development with Swift",
      "Experience with SwiftUI and Combine or Swift Concurrency (async/await)",
      "Familiarity with AVFoundation or live video streaming SDKs",
      "Understanding of App Store review guidelines and release processes",
      "Experience with CI/CD for mobile (Fastlane, Xcode Cloud)",
    ],
    benefits: [
      "Fully remote with $500/month coworking stipend",
      "Home office equipment budget: $3,500",
      "Quarterly team offsites in fun cities",
      "Employee discount on all ShopStream marketplace products",
      "Stock options with early exercise allowed",
    ],
    companyLogo: "/assets/logos/shopstream.png",
    teamSize: "6 mobile engineers (3 iOS, 3 Android)",
    culture: ["Remote-first", "Move fast", "Creator-centric", "Experimental"],
  },
  {
    company: "Ironclad Legal Tech",
    role: "Senior Backend Engineer",
    location: "New York, NY (Hybrid)",
    salary: "$170,000 - $225,000",
    manager: {
      name: "Ananya Gupta",
      title: "Staff Engineer",
      tagline: "Making contracts less painful, one API at a time",
      photo: "/assets/managers/ananya.jpg",
    },
    hr: {
      name: "Patrick Sullivan",
      title: "Head of Talent",
      photo: "/assets/hr/patrick.jpg",
      email: "patrick.sullivan@ironcladlt.com",
      phone: "(646) 555-1367",
    },
    tags: ["Java", "Elasticsearch", "Kafka", "Microservices", "Legal Tech"],
    description:
      "About the Role: Build the backend systems that power our contract lifecycle management platform used by Fortune 500 legal teams.\n\nWhat You'll Do: Design document storage, search, and retrieval services with Elasticsearch. Implement workflow automation engines for contract review and approval. Scale microservices architecture to support enterprise clients.",
    requirements: [
      "5+ years of backend engineering with Java or Kotlin",
      "Experience designing and operating microservices at scale",
      "Proficiency with Elasticsearch, Kafka, or similar distributed systems",
      "Familiarity with document processing, OCR, or NLP pipelines",
      "Experience mentoring engineers and conducting thorough code reviews",
    ],
    benefits: [
      "Top-quartile base salary with annual bonus (10-20%)",
      "Hybrid work with beautiful Flatiron District office",
      "Legal education stipend (CLE credits, law courses, bar prep)",
      "Comprehensive mental health coverage (therapy + coaching)",
      "20 weeks paid parental leave",
    ],
    companyLogo: "/assets/logos/ironclad.png",
    teamSize: "20 backend engineers",
    culture: ["Craft-focused", "Thoughtful", "Customer-driven", "Diverse"],
  },
  {
    company: "Kinetic Fitness",
    role: "Mobile Engineer (Android)",
    location: "Miami, FL (On-site)",
    salary: "$135,000 - $175,000",
    manager: {
      name: "Diego Fernandez",
      title: "Mobile Engineering Manager",
      tagline: "Tech that moves with you. Literally",
      photo: "/assets/managers/diego.jpg",
    },
    hr: {
      name: "Hannah Liu",
      title: "People Operations Specialist",
      photo: "/assets/hr/hannah.jpg",
      email: "hannah.liu@kineticfit.com",
      phone: "(305) 555-1645",
    },
    tags: ["Kotlin", "Jetpack Compose", "Wear OS", "Health Tech"],
    description:
      "About the Role: Build the Android and Wear OS apps for our AI-powered fitness coaching platform with 500K+ users.\n\nWhat You'll Do: Develop workout tracking features with Jetpack Compose. Integrate wearable sensors and Health Connect API for real-time biometric data. Implement on-device ML inference for exercise form analysis.",
    requirements: [
      "3+ years of Android development with Kotlin",
      "Experience with Jetpack Compose and modern Android architecture (MVVM)",
      "Familiarity with Health Connect API or wearable device SDKs",
      "Experience with on-device ML (ML Kit, TFLite)",
      "Understanding of Bluetooth LE for sensor communication",
    ],
    benefits: [
      "Free Kinetic Fitness subscription + equipment package",
      "On-site fitness center with personal training sessions",
      "Beach-adjacent Wynwood office",
      "$200/month wellness reimbursement",
      "Flexible PTO with 2-week minimum vacation",
    ],
    companyLogo: "/assets/logos/kinetic-fitness.png",
    teamSize: "5 Android engineers",
    culture: ["Health-conscious", "Active lifestyle", "User-first", "Agile"],
  },
  {
    company: "Orbit Aerospace",
    role: "Embedded Systems Engineer",
    location: "Denver, CO (On-site)",
    salary: "$145,000 - $195,000",
    manager: {
      name: "Mark Jensen",
      title: "VP of Avionics Software",
      tagline: "Reliable software for unreliable environments. That's our motto",
      photo: "/assets/managers/mark.jpg",
    },
    hr: {
      name: "Diana Kowalski",
      title: "Technical Recruiter",
      photo: "/assets/hr/diana.jpg",
      email: "diana.kowalski@orbitaero.com",
      phone: "(720) 555-1489",
    },
    tags: ["C", "C++", "RTOS", "Embedded", "Aerospace"],
    description:
      "About the Role: Develop flight software for our satellite constellation of 48 low-Earth orbit communications satellites.\n\nWhat You'll Do: Write real-time embedded C/C++ for custom avionics boards. Implement fault-tolerant communication protocols for satellite-to-ground links. Conduct hardware-in-the-loop testing with flight hardware.",
    requirements: [
      "4+ years of embedded C/C++ development",
      "Experience with RTOS (FreeRTOS, VxWorks, or RTEMS)",
      "Understanding of communication protocols (CAN, SPI, I2C, UART)",
      "Familiarity with DO-178C or similar safety-critical standards",
      "Experience with hardware-in-the-loop testing and debugging tools",
    ],
    benefits: [
      "Watch your code launch into space (literally)",
      "Relocation package for Denver area",
      "Security clearance sponsorship available",
      "$1,500/year outdoor recreation stipend",
      "9/80 schedule (every other Friday off)",
    ],
    companyLogo: "/assets/logos/orbit-aerospace.png",
    teamSize: "16 embedded engineers",
    culture: ["Mission-critical", "Precision", "Team trust", "Adventure"],
  },
  {
    company: "Velvet Audio",
    role: "Creative Technologist",
    location: "Los Angeles, CA (Hybrid)",
    salary: "$125,000 - $165,000",
    manager: {
      name: "Kai Nakamura",
      title: "Creative Director of Technology",
      tagline: "Where art meets code. We make the internet sing",
      photo: "/assets/managers/kai.jpg",
    },
    hr: {
      name: "Sophia Reyes",
      title: "Studio HR Coordinator",
      photo: "/assets/hr/sophia.jpg",
      email: "sophia.reyes@velvetaudio.com",
      phone: "(323) 555-1255",
    },
    tags: ["Three.js", "Web Audio API", "GSAP", "Creative Coding"],
    description:
      "About the Role: Design and build immersive audio-visual web experiences for musicians, labels, and global brands.\n\nWhat You'll Do: Prototype interactive installations and album release experiences. Build WebGL and Three.js experiences. Integrate Web Audio API for spatial audio and music visualization.",
    requirements: [
      "3+ years building creative or interactive web experiences",
      "Proficiency with Three.js, WebGL, or creative coding tools (p5.js, TouchDesigner)",
      "Experience with Web Audio API, Tone.js, or similar audio frameworks",
      "Strong visual design sense and portfolio of interactive work",
      "Experience with animation libraries (GSAP, Framer Motion)",
    ],
    benefits: [
      "Access to recording studio and creative equipment",
      "Tickets to concerts and industry events",
      "$3,000 annual creative tools budget",
      "Collaborative workspace in Arts District",
      "Flexible schedule with project-based deadlines",
    ],
    companyLogo: "/assets/logos/velvet-audio.png",
    teamSize: "4 creative technologists",
    culture: ["Artistically bold", "Experimental", "Music-obsessed", "Interdisciplinary"],
  },
  {
    company: "MedVault Health",
    role: "QA Automation Engineer",
    location: "Boston, MA (Hybrid)",
    salary: "$120,000 - $160,000",
    manager: {
      name: "James Okoro",
      title: "Director of Platform Engineering",
      tagline: "Quality is not optional when lives depend on your code",
      photo: "/assets/managers/james.jpg",
    },
    hr: {
      name: "Emily Santos",
      title: "People Operations Lead",
      photo: "/assets/hr/emily-s.jpg",
      email: "emily.santos@medvault.com",
      phone: "(617) 555-0198",
    },
    tags: ["Playwright", "Cypress", "Python", "Healthcare", "CI/CD"],
    description:
      "About the Role: Own the quality strategy for our HIPAA-compliant healthcare data platform used by 200+ hospitals.\n\nWhat You'll Do: Design and implement end-to-end test automation using Playwright and Cypress. Build API test suites for our microservices architecture. Integrate automated tests into CI/CD pipelines.",
    requirements: [
      "3+ years of QA or test automation experience",
      "Proficiency with modern test frameworks (Playwright, Cypress, Selenium)",
      "Experience with API testing and CI/CD integration",
      "Understanding of healthcare compliance (HIPAA) testing requirements",
      "Familiarity with Python or JavaScript for test scripting",
    ],
    benefits: [
      "100% employer-paid health, dental, and vision",
      "401(k) with 6% match",
      "$3,000 home office setup budget",
      "16 weeks parental leave",
      "Annual company retreat",
    ],
    companyLogo: "/assets/logos/medvault.png",
    teamSize: "8 engineers + 3 QA specialists",
    culture: ["Mission-driven", "Security-first", "Empathetic", "Detail-oriented"],
  },
  {
    company: "Fable Interactive",
    role: "Full Stack Developer",
    location: "Austin, TX (On-site)",
    salary: "$130,000 - $170,000",
    manager: {
      name: "Lena Dvorak",
      title: "Lead Interactive Director",
      tagline: "Stories that play back. Experiences you don't forget",
      photo: "/assets/managers/lena.jpg",
    },
    hr: {
      name: "Jesse Morales",
      title: "Studio Recruiter",
      photo: "/assets/hr/jesse.jpg",
      email: "jesse.morales@fableinteractive.com",
      phone: "(512) 555-1523",
    },
    tags: ["Next.js", "TypeScript", "Prisma", "Vercel", "Indie Studio"],
    description:
      "About the Role: Build the web platform and tooling for our narrative-driven interactive game studio.\n\nWhat You'll Do: Develop our creator platform in Next.js where writers publish interactive stories. Build content management APIs with Prisma and PostgreSQL. Implement real-time collaboration features for co-authoring.",
    requirements: [
      "3+ years of full-stack development with React/Next.js",
      "Experience with TypeScript, Prisma, and PostgreSQL",
      "Familiarity with real-time features (WebSockets, collaboration tools)",
      "Interest in interactive storytelling, games, or creative tools",
      "Experience with Vercel or similar deployment platforms",
    ],
    benefits: [
      "Royalty participation on shipped titles",
      "Creative writing workshops and guest speaker series",
      "Flexible hours with core hours 11am-3pm",
      "Game library and media subscription allowance",
      "Dog-friendly East Austin office",
    ],
    companyLogo: "/assets/logos/fable-interactive.png",
    teamSize: "8 engineers + 4 narrative designers",
    culture: ["Story-first", "Playful", "Craft-driven", "Small-team autonomy"],
  },
  {
    company: "Atlas Logistics",
    role: "SRE (Site Reliability Engineer)",
    location: "Chicago, IL (Hybrid)",
    salary: "$155,000 - $210,000",
    manager: {
      name: "Olamide Adeyinka",
      title: "CTO",
      tagline: "Our platform routes 2M shipments daily. Downtime is not an option",
      photo: "/assets/managers/olamide.jpg",
    },
    hr: {
      name: "Catherine Bell",
      title: "VP of People",
      photo: "/assets/hr/catherine.jpg",
      email: "catherine.bell@atlaslogistics.com",
      phone: "(312) 555-1778",
    },
    tags: ["Go", "Kubernetes", "Prometheus", "Terraform", "Supply Chain"],
    description:
      "About the Role: Ensure the reliability of Atlas's route optimization platform processing 2M+ shipments per day across North America.\n\nWhat You'll Do: Design and implement SLOs/SLIs for critical logistics services. Build observability infrastructure with Prometheus, Grafana, and Loki. Automate incident response and develop self-healing systems.",
    requirements: [
      "4+ years in SRE, DevOps, or platform engineering",
      "Proficiency with Go, Python, or similar for tooling and automation",
      "Experience operating Kubernetes at scale in production",
      "Strong understanding of observability (metrics, logs, traces)",
      "Familiarity with incident management processes and blameless postmortems",
    ],
    benefits: [
      "Staff-level equity with accelerated vesting schedule",
      "Flexible hybrid: 2 days in Chicago Loop office",
      "$10,000 annual professional development budget",
      "On-call compensation: $600/week + $250 per incident",
      "Comprehensive health + 401(k) with 5% match",
    ],
    companyLogo: "/assets/logos/atlas-logistics.png",
    teamSize: "45 engineers (SRE team of 6)",
    culture: ["Engineering-led", "High reliability bar", "Autonomous teams", "Continuous improvement"],
  },
  {
    company: "Pulseway Social",
    role: "Frontend Engineer",
    location: "London, UK (Hybrid)",
    salary: "£85,000 - £120,000",
    manager: {
      name: "Roisin Murphy",
      title: "Head of Web Engineering",
      tagline: "Building the next generation of authentic social connection",
      photo: "/assets/managers/roisin.jpg",
      video: "/assets/managers/roisin-intro.mp4",
    },
    hr: {
      name: "Tariq Hassan",
      title: "EMEA Talent Lead",
      photo: "/assets/hr/tariq.jpg",
      email: "tariq.hassan@pulseway.social",
      phone: "+44 20 7946 0958",
    },
    tags: ["React", "GraphQL", "WebSockets", "Performance"],
    description:
      "About the Role: Build the web client for our real-time social platform focused on authentic communities with 5M+ DAU.\n\nWhat You'll Do: Implement live feeds, notification systems, and content moderation UIs. Optimize real-time features using WebSockets and GraphQL subscriptions. Improve Core Web Vitals and loading performance across global CDN.",
    requirements: [
      "3+ years of frontend engineering with React",
      "Experience with real-time systems (WebSockets, SSE, GraphQL subscriptions)",
      "Familiarity with client-side caching (Apollo, urql) and performance optimization",
      "Understanding of web performance, Core Web Vitals, and bundle optimization",
      "Experience with internationalization (i18n) is a plus",
    ],
    benefits: [
      "25 days holiday plus bank holidays",
      "Private health insurance (Bupa)",
      "Cycle-to-work scheme and travel card loan",
      "Central London office with hybrid flexibility (3 days in)",
      "£3,000 annual learning budget",
    ],
    companyLogo: "/assets/logos/pulseway.png",
    teamSize: "14 web engineers",
    culture: ["User-centric", "Fast iteration", "Inclusive", "Open communication"],
  },
  {
    company: "VoltDrive",
    role: "Backend Engineer",
    location: "Berlin, Germany (Hybrid)",
    salary: "€78,000 - €110,000",
    manager: {
      name: "Stefan Richter",
      title: "VP of Platform",
      tagline: "Powering Europe's electric vehicle charging revolution",
      photo: "/assets/managers/stefan.jpg",
    },
    hr: {
      name: "Lena Bauer",
      title: "People Partner",
      photo: "/assets/hr/lena.jpg",
      email: "lena.bauer@voltdrive.de",
      phone: "+49 30 1234 5678",
    },
    tags: ["Go", "gRPC", "IoT", "Automotive", "MQTT"],
    description:
      "About the Role: Build the cloud platform managing real-time charging sessions for 50,000+ EV stations across Europe.\n\nWhat You'll Do: Develop real-time telemetry ingestion services handling 100K+ events/sec via MQTT. Build billing and payment reconciliation services. Design fleet management APIs for enterprise customers.",
    requirements: [
      "3+ years of backend development with Go, Java, or Rust",
      "Experience with IoT protocols (MQTT, AMQP) or telemetry data at scale",
      "Familiarity with gRPC and event-driven architectures",
      "Understanding of payment processing or billing systems",
      "Fluency in English required; German is a plus",
    ],
    benefits: [
      "30 days paid vacation",
      "BVG transit pass (fully covered)",
      "Free EV charging at all VoltDrive stations",
      "Relocation support and visa sponsorship",
      "Dog-friendly Kreuzberg office",
    ],
    companyLogo: "/assets/logos/voltdrive.png",
    teamSize: "12 backend engineers",
    culture: ["Sustainability-driven", "Pragmatic", "Flat hierarchy", "International team"],
  },
  {
    company: "Nexon Biotech",
    role: "Bioinformatics Software Engineer",
    location: "Cambridge, MA (On-site)",
    salary: "$150,000 - $200,000",
    manager: {
      name: "Dr. Fatima Hassan",
      title: "Director of Computational Biology",
      tagline: "Code that accelerates drug discovery by months",
      photo: "/assets/managers/fatima.jpg",
    },
    hr: {
      name: "Ben Crawford",
      title: "Scientific Recruiter",
      photo: "/assets/hr/ben.jpg",
      email: "ben.crawford@nexonbio.com",
      phone: "(617) 555-1138",
    },
    tags: ["Python", "Bioinformatics", "AWS", "Genomics"],
    description:
      "About the Role: Build computational pipelines that analyze genomic and proteomic data to identify drug targets.\n\nWhat You'll Do: Develop and optimize Nextflow/Snakemake pipelines for genomic analysis. Build internal tools for variant calling, RNA-seq, and protein structure prediction. Deploy pipelines on AWS Batch for large-scale parallel processing.",
    requirements: [
      "3+ years of software engineering with Python",
      "Experience with bioinformatics tools (BWA, GATK, Nextflow, or Snakemake)",
      "Understanding of genomics: variant calling, RNA-seq, protein structures",
      "Experience with cloud-based batch processing (AWS Batch, GCP Life Sciences)",
      "MS or PhD in bioinformatics, computational biology, or related field",
    ],
    benefits: [
      "Publication support and conference attendance",
      "On-site lab access for cross-disciplinary learning",
      "Tuition reimbursement up to $10,000/year",
      "Comprehensive health coverage including fertility benefits",
      "Shuttle service from Boston and Cambridge T stops",
    ],
    companyLogo: "/assets/logos/nexon-biotech.png",
    teamSize: "14 computational scientists",
    culture: ["Scientific rigor", "Cross-disciplinary", "Patient-focused", "Innovative"],
  },
  {
    company: "Helix Streaming",
    role: "Data Scientist",
    location: "Toronto, Canada (Hybrid)",
    salary: "CAD $130,000 - $175,000",
    manager: {
      name: "Jean-Pierre Lavoie",
      title: "VP of Product Intelligence",
      tagline: "Content discovery that feels like magic — powered by data",
      photo: "/assets/managers/jp.jpg",
    },
    hr: {
      name: "Samira Patel",
      title: "Senior Recruiter",
      photo: "/assets/hr/samira.jpg",
      email: "samira.patel@helixstream.ca",
      phone: "+1 (416) 555-2041",
    },
    tags: ["Python", "SQL", "Recommendation Systems", "A/B Testing", "Streaming"],
    description:
      "About the Role: Own the data science behind content recommendations for Helix's 8M+ subscriber music and podcast platform.\n\nWhat You'll Do: Build and improve collaborative filtering and content-based recommendation models. Design and analyze A/B experiments for personalization features. Partner with product to optimize discovery algorithms.",
    requirements: [
      "3+ years of data science experience in consumer tech",
      "Strong Python and SQL skills",
      "Experience with recommendation systems or content personalization",
      "Proficiency with experimentation frameworks and causal inference",
      "MS in Statistics, Computer Science, or related quantitative field",
    ],
    benefits: [
      "Premium Helix subscription for life",
      "Hybrid work from downtown Toronto office (2 days in)",
      "RRSP matching up to 5%",
      "Annual tickets to major music festivals",
      "Comprehensive health and dental coverage",
    ],
    companyLogo: "/assets/logos/helix-streaming.png",
    teamSize: "5 data scientists, 3 ML engineers",
    culture: ["Music-first", "Data-informed", "Collaborative", "User-obsessed"],
  },
  {
    company: "Sentry PropTech",
    role: "Full Stack Developer",
    location: "Singapore (On-site)",
    salary: "SGD $120,000 - $170,000",
    manager: {
      name: "Wei Lin Tan",
      title: "Head of Engineering",
      tagline: "Digitizing real estate across Southeast Asia, one building at a time",
      photo: "/assets/managers/weilin.jpg",
    },
    hr: {
      name: "Priya Sharma",
      title: "HR Manager",
      photo: "/assets/hr/priya-s.jpg",
      email: "priya.sharma@sentryproptech.sg",
      phone: "+65 6789 0123",
    },
    tags: ["Next.js", "TypeScript", "PostgreSQL", "PropTech"],
    description:
      "About the Role: Build the platform powering property transactions and smart building analytics for 200+ commercial properties across Singapore, Malaysia, and Indonesia.\n\nWhat You'll Do: Develop interactive floor plans and 3D building visualization tools. Build tenant management and lease administration workflows. Integrate IoT dashboards for smart building energy monitoring.",
    requirements: [
      "3+ years of full-stack experience with React/Next.js and Node.js",
      "Experience with PostgreSQL and REST/GraphQL APIs",
      "Familiarity with geospatial data or mapping libraries (Mapbox, Leaflet)",
      "Comfort working in a fast-moving startup environment",
      "Bonus: Experience with IoT integrations or 3D visualization",
    ],
    benefits: [
      "13th-month salary (AWS — Annual Wage Supplement)",
      "Flexible work arrangements",
      "Annual flight allowance for regional travel",
      "Central CBD office with marina views",
      "Comprehensive medical and dental coverage",
    ],
    companyLogo: "/assets/logos/sentry-proptech.png",
    teamSize: "10 engineers",
    culture: ["Scrappy", "Customer-close", "Regional mindset", "Growth-oriented"],
  },
  {
    company: "Zenith Space Mining",
    role: "Simulation Engineer",
    location: "Houston, TX (On-site)",
    salary: "$160,000 - $220,000",
    manager: {
      name: "Dr. Amara Okonkwo",
      title: "Chief Simulation Architect",
      tagline: "We simulate entire missions before a single bolt is turned",
      photo: "/assets/managers/amara.jpg",
    },
    hr: {
      name: "Kevin Choi",
      title: "Technical Talent Lead",
      photo: "/assets/hr/kevin.jpg",
      email: "kevin.choi@zenithsm.com",
      phone: "(281) 555-1934",
    },
    tags: ["Python", "C++", "Physics Simulation", "Space Tech"],
    description:
      "About the Role: Build high-fidelity simulations of asteroid mining operations and mission planning.\n\nWhat You'll Do: Develop physics simulations for orbital mechanics and robotic arm dynamics. Build resource extraction process models for mission feasibility analysis. Create visualization tools for simulation output.",
    requirements: [
      "4+ years in simulation, physics modeling, or scientific computing",
      "Strong C++ and Python for numerical simulation",
      "Background in physics, aerospace, or mechanical engineering",
      "Experience with simulation frameworks (Gazebo, MuJoCo, or custom engines)",
      "Familiarity with visualization tools (VTK, ParaView, or similar)",
    ],
    benefits: [
      "Front-row seat to the space resource revolution",
      "Relocation assistance to Houston",
      "Access to NASA JSC collaboration programs",
      "$5,000 annual space industry conference budget",
      "Comprehensive benefits with HSA contribution",
    ],
    companyLogo: "/assets/logos/zenith.png",
    teamSize: "9 simulation engineers",
    culture: ["Frontier-minded", "Scientifically rigorous", "Ambitious", "Collaborative"],
  },
  {
    company: "Mosaic Design Co",
    role: "Design Engineer",
    location: "Remote (US)",
    salary: "$140,000 - $180,000",
    manager: {
      name: "Yuki Tanaka",
      title: "Design Systems Lead",
      tagline: "Components that bring products to life — at any scale",
      photo: "/assets/managers/yuki.jpg",
    },
    hr: {
      name: "Andre Williams",
      title: "Remote Talent Partner",
      photo: "/assets/hr/andre.jpg",
      email: "andre.williams@mosaicdesign.co",
      phone: "(888) 555-1856",
    },
    tags: ["React", "Storybook", "Figma", "Accessibility", "Design Systems"],
    description:
      "About the Role: Build and maintain a design system used by 12 product teams across our enterprise SaaS platform.\n\nWhat You'll Do: Develop accessible React components with TypeScript. Write comprehensive documentation in Storybook. Bridge the gap between Figma designs and production code.",
    requirements: [
      "4+ years building UI components in React with TypeScript",
      "Experience maintaining a design system or component library at scale",
      "Proficiency with Figma and design-to-code workflows",
      "Deep understanding of accessibility (ARIA, screen readers, keyboard nav)",
      "Experience with Storybook, Chromatic, or visual regression testing",
    ],
    benefits: [
      "Fully remote with quarterly in-person design sprints",
      "Latest MacBook Pro and design peripherals provided",
      "$2,000 annual home office upgrade budget",
      "Design conference attendance (Config, Clarity, An Event Apart)",
      "Flexible schedule across US time zones",
    ],
    companyLogo: "/assets/logos/mosaic.png",
    teamSize: "6 design engineers",
    culture: ["Craft-obsessed", "Accessible-by-default", "Systematic thinking", "Empowering"],
  },
  {
    company: "ClearSignal Telecom",
    role: "Senior Backend Engineer",
    location: "Remote",
    salary: "$165,000 - $215,000",
    manager: {
      name: "Tomas Eriksson",
      title: "Director of Platform Engineering",
      tagline: "We're rebuilding telecommunications infrastructure from the ground up",
      photo: "/assets/managers/tomas.jpg",
    },
    hr: {
      name: "Jasmine Washington",
      title: "Senior Technical Recruiter",
      photo: "/assets/hr/jasmine.jpg",
      email: "jasmine.washington@clearsignal.io",
      phone: "(720) 555-0934",
    },
    tags: ["Rust", "gRPC", "PostgreSQL", "Telecom", "Distributed Systems"],
    description:
      "About the Role: Build the next-generation telecom platform enabling programmable voice, messaging, and video APIs.\n\nWhat You'll Do: Design and implement high-throughput Rust services for real-time media routing. Build gRPC APIs consumed by thousands of developer customers. Optimize PostgreSQL queries for billing and usage analytics at scale.",
    requirements: [
      "5+ years of backend engineering experience",
      "Proficiency with Rust, Go, or C++ for performance-critical systems",
      "Experience with gRPC, protocol buffers, and API design",
      "Strong PostgreSQL or distributed database experience",
      "Understanding of networking fundamentals (TCP/UDP, WebRTC, SIP)",
    ],
    benefits: [
      "Fully remote with $500/month home office stipend",
      "Equity package with 4-year vesting",
      "Unlimited PTO with 3-week minimum",
      "$4,000 annual learning and conference budget",
      "Health, dental, vision + life and disability insurance",
    ],
    companyLogo: "/assets/logos/clearsignal.png",
    teamSize: "18 backend engineers",
    culture: ["Remote-first", "Deep technical work", "Low-meeting culture", "Open source friendly"],
  },
  {
    company: "Terraform Studios",
    role: "Game Engine Developer",
    location: "Austin, TX (On-site)",
    salary: "$135,000 - $180,000",
    manager: {
      name: "Carlos Rivera",
      title: "Lead Engine Programmer",
      tagline: "Crafting worlds players never want to leave",
      photo: "/assets/managers/carlos.jpg",
    },
    hr: {
      name: "Aisha Thompson",
      title: "Recruiting Coordinator",
      photo: "/assets/hr/aisha.jpg",
      email: "aisha.thompson@terrastudios.com",
      phone: "(512) 555-0314",
    },
    tags: ["C++", "Vulkan", "ECS", "Game Dev", "Rendering"],
    description:
      "About the Role: Help build our proprietary game engine used by 80+ developers on our open-world RPG.\n\nWhat You'll Do: Optimize the rendering pipeline for Vulkan and DirectX 12. Implement entity-component-system architecture for complex game objects. Develop profiling and debugging tools for artists and designers.",
    requirements: [
      "3+ years of C++ development in a game engine or graphics context",
      "Experience with Vulkan, DirectX 12, or Metal rendering APIs",
      "Understanding of entity-component-system (ECS) architecture",
      "Strong math: linear algebra, quaternions, spatial algorithms",
      "Experience profiling and optimizing performance-critical code",
    ],
    benefits: [
      "Royalty bonus on shipped titles",
      "Flexible hours with core overlap 11am-4pm",
      "Game library and console allowance",
      "Dog-friendly office near downtown Austin",
      "Annual game jam week (paid company event)",
    ],
    companyLogo: "/assets/logos/terraform-studios.png",
    teamSize: "22 engine + graphics engineers",
    culture: ["Creative", "Passionate", "Iterative", "Player-focused"],
  },
  {
    company: "GreenCart",
    role: "Senior Data Engineer",
    location: "Portland, OR (Hybrid)",
    salary: "$145,000 - $190,000",
    manager: {
      name: "Jordan Blake",
      title: "Head of Data Platform",
      tagline: "Turning grocery data into sustainable supply chains",
      photo: "/assets/managers/jordan.jpg",
    },
    hr: {
      name: "Megan O'Brien",
      title: "Recruiting Manager",
      photo: "/assets/hr/megan.jpg",
      email: "megan.obrien@greencart.com",
      phone: "(503) 555-1024",
    },
    tags: ["Spark", "Airflow", "BigQuery", "dbt", "Sustainability"],
    description:
      "About the Role: Build and maintain the data infrastructure for our sustainable grocery delivery platform.\n\nWhat You'll Do: Design ETL pipelines with Airflow and dbt for warehouse modeling. Build real-time event streaming for delivery tracking and inventory updates. Enable analytics teams to track food waste reduction and supplier sustainability scores.",
    requirements: [
      "4+ years of data engineering experience",
      "Proficiency with Apache Spark, Airflow, or Dagster",
      "Experience with BigQuery, Snowflake, or Redshift",
      "Strong SQL and experience with dbt or similar transformation tools",
      "Familiarity with data quality frameworks (Great Expectations, Soda, Monte Carlo)",
    ],
    benefits: [
      "Free weekly GreenCart grocery delivery",
      "$100/month bike-to-work incentive",
      "Flexible 4.5-day work week",
      "Composting and sustainability workshops",
      "Stock options in a mission-driven company",
    ],
    companyLogo: "/assets/logos/greencart.png",
    teamSize: "5 data engineers",
    culture: ["Sustainability-first", "Pragmatic", "Curious", "Team-oriented"],
  },
];

async function clearCollection(collectionPath: string) {
  const snapshot = await db.collection(collectionPath).get();
  if (snapshot.empty) {
    console.log(`Collection "${collectionPath}" is already empty.`);
    return;
  }
  const batch = db.batch();
  snapshot.docs.forEach((doc) => batch.delete(doc.ref));
  await batch.commit();
  console.log(`Cleared ${snapshot.size} documents from "${collectionPath}".`);
}

async function seed() {
  console.log("Starting seed...\n");

  console.log("Clearing existing jobs collection...");
  await clearCollection("jobs");

  console.log(`\nSeeding ${jobs.length} jobs...\n`);

  for (let i = 0; i < jobs.length; i++) {
    const job = jobs[i];
    const docRef = db.collection("jobs").doc();
    await docRef.set({ ...job, id: docRef.id });
    console.log(`  [${i + 1}/${jobs.length}] ${job.role} at ${job.company}`);
  }

  console.log(`\nDone! Seeded ${jobs.length} jobs into Firestore.`);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
